force-app/main/default/objects/BusinessLicense/fields/EID__c.field-meta.xml
<CustomField>
    <fullName>EID__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>External ID</inlineHelpText>
    <label>EID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/Percentage_Of_Total_Income__c.field-meta.xml
<CustomField>
    <fullName>Percentage_Of_Total_Income__c</fullName>
    <label>Percentage Of Total Income</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/Provincial_Jurisdiction__c.field-meta.xml
<CustomField>
    <fullName>Provincial_Jurisdiction__c</fullName>
    <label>Provincial Jurisdiction</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alberta</fullName>
            </value>
            <value>
                <fullName>British Columbia</fullName>
            </value>
            <value>
                <fullName>Manitoba</fullName>
            </value>
            <value>
                <fullName>New Brunswick</fullName>
            </value>
            <value>
                <fullName>Newfoundland and Labrador</fullName>
            </value>
            <value>
                <fullName>Northwest Territories</fullName>
            </value>
            <value>
                <fullName>Nova Scotia</fullName>
            </value>
            <value>
                <fullName>Nunavut</fullName>
            </value>
            <value>
                <fullName>Ontario</fullName>
            </value>
            <value>
                <fullName>Prince Edward Island</fullName>
            </value>
            <value>
                <fullName>Saskatchewan</fullName>
            </value>
            <value>
                <fullName>Yukon</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/Total_Annual_Earning__c.field-meta.xml
<CustomField>
    <fullName>Total_Annual_Earning__c</fullName>
    <label>Total Annual Earning</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/testing_buisLicClass.cls
public class testing_buisLicClass {
    
    Public static void UpdateBusinessLicense(
        BusinessLicense [] BusinessLicensArray, //--->acc id---person acc, this is a list without insertion
        String Id //accId----> person acc
        
    ){
        try{
            
            System.debug('BUSINESSLICENSE RECEVED ' + BusinessLicensArray);
            System.debug('ID ' + Id);
            
            List <BusinessLicense> AllBusinessLicense =[SELECT IsActive,EID__c FROM BusinessLicense WHERE AccountId=: Id];
            
            //there are no business licenses since we didnt insert the licenses for person acc
            
            System.debug(' All Business Licenses are:::: ' + AllBusinessLicense);
            
            // INtialize
            map <String,BusinessLicense> AllBusLicMap = new map <String,BusinessLicense>();
            // Put data into map
            for(BusinessLicense BL: AllBusinessLicense)
            {
                //test class no covering this probably because AllBusinessLicense has no data
                BL.IsActive=false;
                AllBusLicMap.put(BL.EID__c, BL);
            }
            
            
            
            for(BusinessLicense BL: BusinessLicensArray)
            {
                //not sure why this isnt being covered
                BL.IsActive=true;
                AllBusLicMap.put(BL.EID__c, BL);
            }
            
            
            //BusinessLicensArray.IsActive= true;
            //not covered 
            //
            System.debug('AllBusLicMap.values() ' + AllBusLicMap.values());
            upsert AllBusLicMap.values() EID__c;
            
            
        }
        catch(exception e){
            
        }
    }
    
    
    public static void getBuisnessLicenseData(String AccId){
        try {
            List<BusinessLicense> listOfBLicense = new List<BusinessLicense>();
            listOfBLicense = [Select Percentage_Of_Total_Income__c,Total_Annual_Earning__c,Provincial_Jurisdiction__c,Name
                              from BusinessLicense where ContactId =: AccId and IsActive = True  ];
            
            SYSTEM.debug('listOfBLicense' +listOfBLicense);
            
        } catch (Exception e) {
            
        }
    }
}