force-app/main/default/objects/Short_Rate__mdt/Short_Rate__mdt.object-meta.xml
<CustomObject>
    <label>Short Rate Cancellation</label>
    <pluralLabel>Short Rate Cancellations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Short_Rate__mdt/fields/Days_Policy_In_Force__c.field-meta.xml
<CustomField>
    <fullName>Days_Policy_In_Force__c</fullName>
    <label>Days Policy In Force</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Short_Rate__mdt/fields/Percentage_of_Premium_Retained__c.field-meta.xml
<CustomField>
    <fullName>Percentage_of_Premium_Retained__c</fullName>
    <label>Percentage of Premium Retained</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/Testing_Class.cls
public class Testing_Class {
    
    public static string  test(){
        Short_Rate__mdt[] shortRate = 
        [Select Days_Policy_In_Force__c,Percentage_of_Premium_Retained__c from Short_Rate__mdt];
    Set<decimal> SortRateData = new Set<decimal>();
    for(Short_Rate__mdt record:shortRate)
    {
        SortRateData.add(record.Days_Policy_In_Force__c);
    }   
    
    System.debug(SortRateData);
    return 'success';    
    }
    
  
    
}