force-app/main/default/objects/Extended_Report_Period__c/Extended_Report_Period__c.object-meta.xml
<CustomObject>
    <description>Used to capture extended reporting period of Quote/Policy</description>
    <label>Extended Report Period</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Extended Report Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Extended_Report_Period__c/fields/Additional_Premium__c.field-meta.xml
<CustomField>
    <fullName>Additional_Premium__c</fullName>
    <inlineHelpText>Additional premium percentage of an extended reporting period</inlineHelpText>
    <label>Additional Premium</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Extended_Report_Period__c/fields/Extended_Report_Period__c.field-meta.xml
<CustomField>
    <fullName>Extended_Report_Period__c</fullName>
    <inlineHelpText>What is the period of extended reporting ?</inlineHelpText>
    <label>Extended Report Period</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Extended_Report_Period__c/fields/Extended_Reporting_Period_Category__c.field-meta.xml
<CustomField>
    <fullName>Extended_Reporting_Period_Category__c</fullName>
    <inlineHelpText>Choose extended reporting period category</inlineHelpText>
    <label>Extended Reporting Period Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Days</fullName>
            </value>
            <value>
                <fullName>Months</fullName>
            </value>
            <value>
                <fullName>Years</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Extended_Report_Period__c/fields/months_difference__c.field-meta.xml
<CustomField>
    <fullName>months_difference__c</fullName>
    <formula>IF(
(Policy__r.ExpirationDate  - NOW()) / 365 * 12 &lt; 1, 1, (Policy__r.ExpirationDate  - NOW()) / 365 * 12
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>months difference</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Extended_Report_Period__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Policy of an extended reporting period.</inlineHelpText>
    <label>Policy</label>
    <referenceTo>InsurancePolicy</referenceTo>
    <relationshipLabel>Extended Report Periods</relationshipLabel>
    <relationshipName>Extended_Report_Periods</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Extended_Report_Period__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product Lookup</description>
    <inlineHelpText>Associated Product</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Extended Report Periods</relationshipLabel>
    <relationshipName>Extended_Report_Periods</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Extended_Report_Period__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Quote of an extended reporting period</inlineHelpText>
    <label>Quote</label>
    <referenceTo>Quote2__c</referenceTo>
    <relationshipLabel>Extended Report Periods</relationshipLabel>
    <relationshipName>Extended_Report_Periods</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Extended_Report_Period__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Current status of ERP</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Drat</fullName>
            </value>
            <value>
                <fullName>Activated</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/Broker__c.field-meta.xml
<CustomField>
    <fullName>Broker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Broker who is managing the policy</inlineHelpText>
    <label>Broker Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/Brokerage__c.field-meta.xml
<CustomField>
    <fullName>Brokerage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Brokerage firm who is managing the policy</inlineHelpText>
    <label>Brokerage</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Brokerage</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Referred Policies</relationshipLabel>
    <relationshipName>Insurance_Policies1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/Commission__c.field-meta.xml
<CustomField>
    <fullName>Commission__c</fullName>
    <inlineHelpText>Commission given to brokerage firm</inlineHelpText>
    <label>Commission</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/Extended_Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Extended_Reporting_Period__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>ERP purchased on policy</inlineHelpText>
    <label>Purchased ERP</label>
    <referenceTo>Extended_Report_Period__c</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/months_difference__c.field-meta.xml
<CustomField>
    <fullName>months_difference__c</fullName>
    <formula>IF(
(ExpirationDate - NOW()) / 365 * 12 &lt; 1, 1, (ExpirationDate - NOW()) / 365 * 12
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>months difference</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Quote from where policy originated.</inlineHelpText>
    <label>Source Quote</label>
    <referenceTo>Quote2__c</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote2__c/Quote2__c.object-meta.xml
<CustomObject>
    <description>Quote is a bundle of different products with Policy Options and Product Coverages, customized specifically for each opportunity. This object will only be associated with Business companies. There can be multiple quotes associated with the opportunity, to track multiple quotes, there will be a status field which will have options like Draft, Activated, Rejected and only one quote can have ‘activated’ status under one opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote2__c/fields/Broker__c.field-meta.xml
<CustomField>
    <fullName>Broker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Broker who is managing the quote</inlineHelpText>
    <label>Broker</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Account.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Brokerage_Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote2__c/fields/Commission__c.field-meta.xml
<CustomField>
    <fullName>Commission__c</fullName>
    <inlineHelpText>Commission given to the brokerage firm</inlineHelpText>
    <label>Commission</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quote2__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Product offered for this quote</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote2__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Quote&apos;s Current Status</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Quoted</fullName>
            </value>
            <value>
                <fullName>Activated</fullName>
                <label>Issued</label>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/getAllExtenedReportPeriod.cls
public with sharing class getAllExtenedReportPeriod {
    
    public static Account acc = new Account();
    
    @AuraEnabled(cacheable=true)
    public static List<OptionWrapper> getAllERP(){
        List<OptionWrapper> TypesList = new List<OptionWrapper>();       
        
        acc = PersonInformation.getAccountRecord(); 
        
        List<Extended_Report_Period__c> listofERP = [Select id, Name,
                                                     Additional_Premium__c,Extended_Report_Period__c,
                                                     Policy__c,
                                                     Extended_Reporting_Period_Category__c,
                                                     Policy__r.NameInsuredId, 
                                                     Policy__r.PremiumAmount,Policy__r.DateRenewed,
                                                     Policy__r.Status , policy__c                                                       
                                                     from Extended_Report_Period__c where 
                                                     Policy__r.NameInsuredId =: acc.id
                                                    AND Status__c = 'Activated']; 
        
        for( Extended_Report_Period__c pickListVal : listofERP){

            Decimal amount  = pickListVal.Policy__r.PremiumAmount * pickListVal.Additional_Premium__c;

            TypesList.add(new OptionWrapper(pickListVal.Policy__r.Status,pickListVal.id, amount/100 + ' (' + pickListVal.Additional_Premium__c +'% of '+ pickListVal.Policy__r.PremiumAmount + ' for ' + pickListVal.Extended_Report_Period__c + ' ' +pickListVal.Extended_Reporting_Period_Category__c + ')') );
        }
        
        If(TypesList.size() > 0){
        System.debug('List of extened report period::' + listofERP);
        return TypesList;     
       }
        
        else{
            
            return null;
        }
    } 
    
    
     
    @AuraEnabled(cacheable=true)
    public static Extended_Report_Period__c getSelectedERP(Id selectedOption){
        List<OptionWrapper> TypesList = new List<OptionWrapper>();       
        
        acc = PersonInformation.getAccountRecord();
        
        List<Extended_Report_Period__c> listofERP = [Select id, Name,Policy__r.Quote__r.Product__c,Policy__r.Broker__c,Policy__r.Brokerage__c,
                                                     Additional_Premium__c,Extended_Report_Period__c,Policy__r.ProductId,Policy__r.Quote__c,
                                                     Extended_Reporting_Period_Category__c,Policy__r.NameInsuredId,Policy__r.Commission__c, 
                                                     Policy__r.PremiumAmount,Policy__r.Status,Policy__r.DateRenewed,months_difference__c                                                           
                                                     from Extended_Report_Period__c where Id =: selectedOption]; 
        return listofERP[0];
        
    } 
    
    
    public class OptionWrapper {
        @AuraEnabled
        public String PolicyStatus {get; set;}
        @AuraEnabled
        public String label {get; set;}
        @AuraEnabled
        public String value {get; set;}
        
        public OptionWrapper(String PolicyStatus,String value, String label) {
            this.PolicyStatus = PolicyStatus;
            this.label = label;
            this.value = value;
        }
    }
    
     @AuraEnabled
    public static string updatePolicyRecord(string policyId, id erpid){
  
    InsurancePolicy policy = new InsurancePolicy();
        
        policy = [Select name, Extended_Reporting_Period__c  from InsurancePolicy where id=: policyId];
    
        policy.Extended_Reporting_Period__c = erpid;
        policy.Status   = 'Cancelled';
        
        try{
        update policy;
        return 'Policy Updated Successfully';
        
        }
        catch(Exception e){

            System.debug(Logginglevel.ERROR, e.getMessage());
            throw new AuraHandledException(e.getMessage());
        }

        
    } 
    
    
    @AuraEnabled
    public static  AcctSeed__Billing__c getOldERPInvoice(string accountId){
  
    List<AcctSeed__Billing__c> billing = [Select Id,Name,Policy__c,AcctSeed__Customer__c,Extended_Report_Period__c
                                         From AcctSeed__Billing__c Where
                                         AcctSeed__Customer__c =: accountId 
                                         AND Extended_Report_Period__c != Null];
           
        system.debug(billing);
          
        
          if(billing.size()>0){               
          return billing[0];    
          }
          
           else{
          return null; 
       }
    
       }    
    
    
    
    
}