force-app/main/default/objects/Account/fields/Application_Current_Stage__c.field-meta.xml
<CustomField>
    <fullName>Application_Current_Stage__c</fullName>
    <description>This is hidden field used in development process of Register and Purchase.</description>
    <label>Application Current Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>Personal Information</fullName>
            </value>
            <value>
                <fullName>Eligibility Test</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Broker_Contact__c.field-meta.xml
<CustomField>
    <fullName>Broker_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Broker who is managing the account</inlineHelpText>
    <label>Broker</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Brokerage</value>
        </filterItems>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Brokerage_Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Brokerage_Account__c.field-meta.xml
<CustomField>
    <fullName>Brokerage_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Brokerage firm who is managing the account</inlineHelpText>
    <label>Brokerage</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Brokerage</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Clients</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/FinServ__Status__c.field-meta.xml
<CustomField>
    <fullName>FinServ__Status__c</fullName>
    <inlineHelpText>Current Status of an account. Prospect,Prospect,Submission, Quote, Bound, Closed</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Submission</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Bound</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/HiddenAccount__c.field-meta.xml
<CustomField>
    <fullName>HiddenAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sponsored Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (HiddenAccount)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/IBC_Code__c.field-meta.xml
<CustomField>
    <fullName>IBC_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>IBC code of an account</inlineHelpText>
    <label>IBC Code</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Program_Audience__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>IBC Code</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Program_Audience__c</referenceTo>
    <relationshipLabel>Accounts (IBC Code)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Program_Audience__c.field-meta.xml
<CustomField>
    <fullName>Program_Audience__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Program Audience of an account.</inlineHelpText>
    <label>Program Type</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Program_Audience__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Program Type</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Program_Audience__c</referenceTo>
    <relationshipLabel>Sponsored Company</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Username</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <description>This will hold information about the individual that can be sponsored company’s agents and clients of the Open Market Program.</description>
    <label>Person Account</label>
</RecordType>

force-app/main/default/objects/Program_Audience__c/Program_Audience__c.object-meta.xml
<CustomObject>
    <description>Used to capture Program Type and IBC Code</description>
    <label>Program Type/ IBC Code</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Type/ IBC Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Audience__c/fields/IBC_Code__c.field-meta.xml
<CustomField>
    <fullName>IBC_Code__c</fullName>
    <label>IBC Code</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SelfRegisterController.cls
global without sharing class SelfRegisterController {

    
        //gets list of contacts. If contact already exists, return true, if not then return false
        @AuraEnabled
        public static boolean getContactList(String Email) {
            //return [SELECT Id FROM Account where PersonEmail =: email limit 1];
            List<Account> account_data = [Select Id from Account where PersonEmail =: email limit 1];
            boolean check = false;
            if(account_data.size()>0){
                    check =  true;
            }
            return check;
        }
    

    //This method saves person account records
    //these person account must be affiliated to a business account first, the accId in the params is account id of the parent account
    @AuraEnabled
    public static void saveAccountRecord(String firstname, String lastname, String email, String username, String phone , String accId){
        //boolean email_exists = EmailExists(email);
        RecordType recId = [Select Id from RecordType where developerName =: 'PersonAccount' limit 1];
        
        Account objAcc = new Account();
        objAcc.firstname = firstname;
        objAcc.lastname = lastname;
        objAcc.PersonEmail = email;
        objAcc.Username__c = username;
        objAcc.phone = phone;
        objAcc.RecordTypeId = recId.id;
            //'0126g000000zIHRAA2';

        System.debug('Account Record::' + objAcc);

        System.debug('Account lastName::' + objAcc.lastname);
        System.debug('Account Phone::' + objAcc.phone);

        System.debug('Account Username::' + objAcc.Username__c);
        System.debug('Account email::' + objAcc.PersonEmail);
        System.debug('Account has the values::' + objAcc);
        
        

        try{
        
            Account  parentAccount = [Select name , id , HiddenAccount__r.IBC_Code__c,program_audience__c , brokerage_account__c, Broker_Contact__c  from Account where id =: accId];
			
            // First Check the provided accId exist in Salesforce or not 
            
                objAcc.HiddenAccount__c = accId;
                objAcc.brokerage_account__c = parentAccount.brokerage_account__c;
                objAcc.Broker_Contact__c = parentAccount.Broker_Contact__c;
                objAcc.program_audience__c = parentAccount.program_audience__c;
                objAcc.IBC_Code__c = parentAccount.HiddenAccount__r.IBC_Code__c;
                objAcc.Application_Current_Stage__c = 'Not Started';
                objAcc.FinServ__Status__c = 'Prospect';
                insert objAcc;
                
                System.debug('Account is inserted::' + objAcc);
                System.debug('Account Id::' + accId);
                
                Account perAcc = [Select id, firstname, lastname, PersonContactId from Account where id =: objAcc.Id];
                
                AccountContactRelation accConRel = new AccountContactRelation();
                accConRel.AccountId = accId;
                accConRel.ContactId = perAcc.PersonContactId;
                accConRel.Roles = 'Employee';
                accConRel.IsActive = TRUE;
                insert accConRel;
                
            
            

            
            
            //insert usr;
        }
        catch(Exception ex) {
            System.debug('Error message in save account'+ex);
            throw new AuraHandledException('Email Already Exists');
            //System.debug('Exception Error::' + ex.getMessage());
            
        }
    }
    
    //checks status of business account (parent acc)
    @AuraEnabled
    public static Boolean CurrentAccStatus(string objAcc){
        //check if account id is null
            if(objAcc != ''){
                
        List<Account> AccStatus = [Select FinServ__Status__c From Account Where Id=: objAcc Limit 1];
        
        if(AccStatus.size() >0){
            if(AccStatus[0].FinServ__Status__c == 'Bound'){
                return true;
            }
        }
        
        
    }
            return false;
    }
}