force-app/main/default/objects/Account/fields/Applicable_License__c.field-meta.xml
<CustomField>
    <fullName>Applicable_License__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicable License</label>
    <referenceTo>BusinessLicense</referenceTo>
    <relationshipLabel>Accounts (Applicable License)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Assigned_License__c.field-meta.xml
<CustomField>
    <fullName>Assigned_License__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned License</label>
    <referenceTo>BusinessLicense</referenceTo>
    <relationshipLabel>Accounts (Assigned License)</relationshipLabel>
    <relationshipName>Accounts2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Brokerage_Account__c.field-meta.xml
<CustomField>
    <fullName>Brokerage_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Brokerage firm who is managing the account</inlineHelpText>
    <label>Brokerage</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Brokerage</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Clients</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Business_License__c.field-meta.xml
<CustomField>
    <fullName>Business_License__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business License</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.HiddenAccount__c</field>
            <operation>equals</operation>
            <valueField>BusinessLicense.AccountId</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>BusinessLicense</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Applicant_Response__c/Applicant_Response__c.object-meta.xml
<CustomObject>
    <description>Used to capture response of a question provided by an applicant</description>
    <label>Applicant Response</label>
    <nameField>
        <label>Applicant Answer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applicant Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Applicant_Response__c/fields/Program_Application__c.field-meta.xml
<CustomField>
    <fullName>Program_Application__c</fullName>
    <inlineHelpText>Applicant response on the program application</inlineHelpText>
    <label>Program Application</label>
    <referenceTo>Program_Application__c</referenceTo>
    <relationshipLabel>Applicant Responses</relationshipLabel>
    <relationshipName>Applicant_Responses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Applicant_Response__c/fields/Program_Question__c.field-meta.xml
<CustomField>
    <fullName>Program_Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Program question of which applicant has answered</inlineHelpText>
    <label>Program Question</label>
    <referenceTo>Program_Question__c</referenceTo>
    <relationshipLabel>Applicant Responses</relationshipLabel>
    <relationshipName>Question_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Applicant_Response__c/fields/Program_Question_Answer__c.field-meta.xml
<CustomField>
    <fullName>Program_Question_Answer__c</fullName>
    <inlineHelpText>Correct answer of the question of a specific Program Type</inlineHelpText>
    <label>Program Question Answer</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/EID__c.field-meta.xml
<CustomField>
    <fullName>EID__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>External ID</inlineHelpText>
    <label>EID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/Licenses_Type__c.field-meta.xml
<CustomField>
    <fullName>Licenses_Type__c</fullName>
    <label>Licenses Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>LLQP</fullName>
            </value>
            <value>
                <fullName>MFDA</fullName>
            </value>
            <value>
                <fullName>IIROC</fullName>
            </value>
            <value>
                <fullName>EMD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/Newly_License_Check__c.field-meta.xml
<CustomField>
    <fullName>Newly_License_Check__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Newly License Check</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/Percentage_Of_Total_Income__c.field-meta.xml
<CustomField>
    <fullName>Percentage_Of_Total_Income__c</fullName>
    <label>Percentage Of Total Income</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/Provincial_Jurisdiction__c.field-meta.xml
<CustomField>
    <fullName>Provincial_Jurisdiction__c</fullName>
    <label>Provincial Jurisdiction</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alberta</fullName>
            </value>
            <value>
                <fullName>British Columbia</fullName>
            </value>
            <value>
                <fullName>Manitoba</fullName>
            </value>
            <value>
                <fullName>New Brunswick</fullName>
            </value>
            <value>
                <fullName>Newfoundland and Labrador</fullName>
            </value>
            <value>
                <fullName>Northwest Territories</fullName>
            </value>
            <value>
                <fullName>Nova Scotia</fullName>
            </value>
            <value>
                <fullName>Nunavut</fullName>
            </value>
            <value>
                <fullName>Ontario</fullName>
            </value>
            <value>
                <fullName>Prince Edward Island</fullName>
            </value>
            <value>
                <fullName>Saskatchewan</fullName>
            </value>
            <value>
                <fullName>Yukon</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Licensed Assistant</fullName>
            </value>
            <value>
                <fullName>Licensed Advisor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/Total_Annual_Earning__c.field-meta.xml
<CustomField>
    <fullName>Total_Annual_Earning__c</fullName>
    <label>Total Annual Earning</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <description>This will hold information about the individual that can be sponsored company’s agents and clients of the Open Market Program.</description>
    <label>Person Account</label>
</RecordType>

force-app/main/default/objects/Program_Application__c/Program_Application__c.object-meta.xml
<CustomObject>
    <label>Program Application</label>
    <nameField>
        <label>Program Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Application</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Application__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>A person account who applied for eligibility test</inlineHelpText>
    <label>Program Applicant</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Program Application</relationshipLabel>
    <relationshipName>Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_Application__c/fields/Broker__c.field-meta.xml
<CustomField>
    <fullName>Broker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Broker who is managing the application</inlineHelpText>
    <label>Broker</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Program Application</relationshipLabel>
    <relationshipName>Program_Application</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_Application__c/fields/Brokerage_Account__c.field-meta.xml
<CustomField>
    <fullName>Brokerage_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Brokerage firm who is managing the application</inlineHelpText>
    <label>Brokerage Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Program Application (Brokerage Account)</relationshipLabel>
    <relationshipName>Program_Application</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_Application__c/fields/Business_License__c.field-meta.xml
<CustomField>
    <fullName>Business_License__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Business license of program application</inlineHelpText>
    <label>Business License</label>
    <referenceTo>BusinessLicense</referenceTo>
    <relationshipLabel>Program Application</relationshipLabel>
    <relationshipName>Program_Application</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Name to identify details of a program application</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Saved</fullName>
            </value>
            <value>
                <fullName>Approved with condition</fullName>
            </value>
            <value>
                <fullName>Approval workflow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program_Application__c/fields/Submission_Date__c.field-meta.xml
<CustomField>
    <fullName>Submission_Date__c</fullName>
    <inlineHelpText>Submission date of a program application</inlineHelpText>
    <label>Submission Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Program_Question__c/Program_Question__c.object-meta.xml
<CustomObject>
    <description>Used to capture question of a Program Type</description>
    <label>Program Question</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Program Question Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Question__c/fields/Business_License__c.field-meta.xml
<CustomField>
    <fullName>Business_License__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Questions for the business license</inlineHelpText>
    <label>Business License</label>
    <referenceTo>BusinessLicense</referenceTo>
    <relationshipLabel>Program Questions</relationshipLabel>
    <relationshipName>Program_Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_Question__c/fields/Correct_Answer__c.field-meta.xml
<CustomField>
    <fullName>Correct_Answer__c</fullName>
    <inlineHelpText>Correct answer of the question of a specific Program Type</inlineHelpText>
    <label>Correct Answer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Program_Question__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <inlineHelpText>Question of the Program Type</inlineHelpText>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Program Questions</relationshipLabel>
    <relationshipName>Program_Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Program_Question__c/fields/ReponseField__c.field-meta.xml
<CustomField>
    <fullName>ReponseField__c</fullName>
    <inlineHelpText>hidden field on backend for .js response value in Eligibility Question in product info</inlineHelpText>
    <label>ReponseField</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{000}</displayFormat>
        <label>Question Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Question_Description__c.field-meta.xml
<CustomField>
    <fullName>Question_Description__c</fullName>
    <inlineHelpText>Stated the question</inlineHelpText>
    <label>Question Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>What is the type of question?</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Pick list</fullName>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/GetAccLicenses.cls
public  without sharing class GetAccLicenses {
    @AuraEnabled
    public static List<BusinessLicense> GetAccLicenses(String accountId) {

        system.debug(accountId);
        //list to get busines licenses of that account
        List <BusinessLicense> ListBusLicenses = [Select name, Id, Licenses_Type__c, Role__c, Newly_License_Check__c 
        from BusinessLicense where AccountId =: accountId];

        return ListBusLicenses ;

    }
    @AuraEnabled
    public static List<Program_Question__c> ProgramQuestions(string accountId ,String Type){
        system.debug('here is acc id: '+accountId);

        List<Program_Question__c> AllProgramQuestions = [Select Id, Question__c ,Correct_Answer__c,
        Question__r.Question_Description__c,Business_License__r.Licenses_Type__c,  Question__r.Type__c, ReponseField__c from Program_Question__c where Business_License__r.AccountId =: accountId and Business_License__r.Licenses_Type__c =:Type ];

        return AllProgramQuestions;
    }

    @AuraEnabled
    public static List<String> getPickList(String objectName, String fieldName) {
        List<String> values = new List<String>();
        List<Schema.DescribeSobjectResult> results = Schema.describeSObjects(new List<String>{objectName});
        
        for(Schema.DescribeSobjectResult res : results) {
            for (Schema.PicklistEntry entry : res.fields.getMap().get(fieldName).getDescribe().getPicklistValues()) {
                if (entry.isActive()) {
                    values.add(entry.getValue());
                }
            }
        }
        return values;
    }

    @AuraEnabled
    public static List<Account> getPickListAccounts(String AccountName, String DevName, String [] NotIn){
        try {
            String qry = '%' + AccountName+'%';
            
            List<Account> names = new List<Account>();
            System.debug(AccountName);

            return [Select name,Id from Account where name like :qry and RecordType.DeveloperName=:DevName
                    and id not in :NotIn ];
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static void CreateAccConRelation(AccountContactRelation [] AccountContactRel){
        try {
            
            Database.upsert(AccountContactRel, False);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static AccountContactRelation [] getAccConRelation(String ContactId){
        try {
            return [Select AccountId,ContactId, account.name from AccountContactRelation where ContactId=:ContactId limit 10];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    @AuraEnabled
    public static list<BusinessLicense> GetBusinessLicense(String accountId, String NameOfLicense){
    System.debug('Account ID ==> ' + accountId);
    System.debug('Name Of License ==> ' + NameOfLicense);
    List<BusinessLicense> LicenseData = 
    [Select AccountId,Name,Percentage_Of_Total_Income__c,Total_Annual_Earning__c,Provincial_Jurisdiction__c from BusinessLicense where AccountId =: accountId and Name =: NameOfLicense];
    System.debug('License Data ==> ' + LicenseData);
    return LicenseData;
    }

    @AuraEnabled
    public static List<BusinessLicense> getBuisnessLicenseData(String AccId){
        try {
            List<BusinessLicense> listOfBLicense = new List<BusinessLicense>();
            listOfBLicense = [Select Percentage_Of_Total_Income__c,Total_Annual_Earning__c,Provincial_Jurisdiction__c,Name
            from BusinessLicense where AccountId =: AccId and IsActive =True  ];
// and Status ='Verified'
            return listOfBLicense;
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }


    @AuraEnabled
    Public static void UpdateBusinessLicense(
    BusinessLicense [] BusinessLicensArray, 
    string externalId,
    String Id,
    String ApplicableLicense,
    String AssignedLicense,
    List<Producer> InsuranceList
    ){
    try{
        System.debug('BUSINESSLICENSE RECEVED ' + BusinessLicensArray);
        List <BusinessLicense> AllBusinessLicense = new List<BusinessLicense>();
        AllBusinessLicense =[SELECT IsActive,EID__c FROM BusinessLicense WHERE AccountId=: Id];
        System.debug(' All Business Licenses are:::: ' + AllBusinessLicense);

            // INtialize
            map <String,BusinessLicense> AllBusLicMap = new map <String,BusinessLicense>();
            // Put data into map
            for(BusinessLicense BL: AllBusinessLicense)
            {
                BL.IsActive=false;
                AllBusLicMap.put(BL.EID__c, BL);
            }
            
        Account acc = new Account();
        acc.Id = Id;
        acc.Applicable_License__c = ApplicableLicense;
        acc.Assigned_License__c = AssignedLicense;
        for(BusinessLicense BL: BusinessLicensArray)
            {
                BL.IsActive=true;
                AllBusLicMap.put(BL.EID__c, BL);
            }
        
        
        //BusinessLicensArray.IsActive= true;
        upsert AllBusLicMap.values() EID__c;
        update acc;
        insert InsuranceList;
        //upsert BusinessLicensArray EID__c;
    }
    catch(exception e){
        System.debug('UpdateBusinessLicense error' + e);
    }
}
    @AuraEnabled
    Public static void InsertProgramApplication(
        String Name,
        String BrokerageAccount,
        String Broker,
        String Status,
        String Account,
        String [] quesArray,
        String [] ansByUser,
        String [] correctAns,
        String BusinessLicense
        // Program_Application__c obj
    ){
       
        Program_Application__c ProgramApplication = new Program_Application__c();
        ProgramApplication.Name = Name;
        ProgramApplication.Broker__c = Broker;
        ProgramApplication.Brokerage_Account__c=BrokerageAccount;
        ProgramApplication.Status__c=Status;
        ProgramApplication.Account__c=Account;
        ProgramApplication.Business_License__c = BusinessLicense;
        ProgramApplication.Submission_Date__c = Date.today();
        ProgramApplication.RecordTypeId = '012f0000000foonAAA';
        insert ProgramApplication;
        // System.debug('Program app Obj ' + obj);
        List<Applicant_Response__c> ListOfQuestions = new List<Applicant_Response__c>();
        for(integer i =0; i < quesArray.size();i++){
            Applicant_Response__c newRes = new Applicant_Response__c();
            newRes.Program_Application__c = ProgramApplication.Id;         
            newRes.Program_Question__c = quesArray[i];      
            newRes.Program_Question_Answer__c=correctAns[i];    
            newRes.Name=ansByUser[i];
            ListOfQuestions.add(newRes);
        }
        try{
            insert ListOfQuestions;
        }
        catch(exception e ){
            System.debug('InsertProgramApplication error ' + e);
        }
    }

    
    

    @AuraEnabled
    Public static void UpdateLicenseFields(
    String[] Licenses, 
    String[] Province,
    Double[] PercentageTotalIncome,
    Double[] totalAnualEarning,
    String ID,
    String ApplicableLicense,
    String AssignedLicense,
    String ProgramApplication_Name,
    String ProgramApplication_Status,
    String ProgramApplication_BrokerageAcc,
    String ProgramApplication_BrokerageCon,
    String [] Questions,
    String [] CorrectAns,
    String [] UserAns,
    String Role
    
    )
    {
        SYSTEM.debug('QUESTIONS + ANS ' );
        Account personAccount = new Account();
        Program_Application__c ProgramApplication = new Program_Application__c();
        ProgramApplication.Name = ProgramApplication_Name;
        ProgramApplication.Status__c = ProgramApplication_Status;
        ProgramApplication.Brokerage_Account__c = ProgramApplication_BrokerageAcc;
        ProgramApplication.Broker__c = ProgramApplication_BrokerageCon;
        ProgramApplication.RecordTypeId = '012f0000000foonAAA';
        ProgramApplication.Account__c = ID;
        // ProgramApplication.Submission_Date__c = DateTime.now();
        insert ProgramApplication;
        List<Applicant_Response__c> ListOfQuestions = new List<Applicant_Response__c>();

        SYSTEM.debug('LENGTH OF QUESTIONS ==== ' + Questions.size()) ;
        for(integer i =0; i < Questions.size(); i++){
            SYSTEM.debug('Questions LOOP RUNNING') ;
            Applicant_Response__c newRes = new Applicant_Response__c();
            SYSTEM.debug('Program_Application__c ===>' + ProgramApplication.Id) ;
            newRes.Program_Application__c = ProgramApplication.Id;
            SYSTEM.debug('Program_Question__c  ===>' + Questions[i]) ;
            newRes.Program_Question__c = Questions[i];
            SYSTEM.debug('Program_Question_Answer__c  ===>' + CorrectAns[i]) ;
            newRes.Program_Question_Answer__c=CorrectAns[i];
            SYSTEM.debug('Program_Question_Answer__c  ===>' + UserAns[i]) ;
            newRes.Name=UserAns[i];
            
            ListOfQuestions.add(newRes);
        }
        insert ListOfQuestions;

        personAccount.Applicable_License__c = ApplicableLicense;
        personAccount.Assigned_License__c = AssignedLicense;
        personAccount.Id = ID;
        System.debug('Size of LISTS RECIEVED:::::  '+Licenses.size());
        SYSTEM.DEBUG('Licnse ===>' + Licenses);
            System.DEBUG('PROVINCES===> '+ Province);
            SYSTEM.DEBUG('PercentageTotalIncome ===>' + PercentageTotalIncome);
            SYSTEM.DEBUG('totalAnualEarning ===>' + totalAnualEarning);
            SYSTEM.DEBUG('ID ===>' + ID);
            SYSTEM.DEBUG('Role ===>' + Role);
            
        List<BusinessLicense> ListOfUpdateLicense = new List<BusinessLicense>();
        
        SYSTEM.DEBUG('RUNNING FOR LOOP::::::::::::::');
        for(integer i=0 ; i<Licenses.size();i++){
            BusinessLicense temp = new BusinessLicense();
            temp.AccountId = ID;
            temp.Name= Licenses[i];
            temp.Percentage_Of_Total_Income__c= PercentageTotalIncome[i];
            temp.Total_Annual_Earning__c= totalAnualEarning[i];
            temp.Provincial_Jurisdiction__c = Province[i];
            temp.Role__c = Role;
            temp.RecordTypeId ='012f0000000lHalAAE';
            SYSTEM.DEBUG('temp.AccountId '+temp.AccountId );
           
            
            SYSTEM.DEBUG('temp.Name '+temp.Name );
            
            
            SYSTEM.DEBUG('temp.Percentage_Of_Total_Income__c '+temp.Percentage_Of_Total_Income__c );
            
            SYSTEM.DEBUG('temp.Total_Annual_Earning__c '+temp.Total_Annual_Earning__c );
            ListOfUpdateLicense.add(temp);

            
        }
        System.debug('LIST SIZE==> ' + ListOfUpdateLicense.size());
        for(integer i = 0; i < ListOfUpdateLicense.size(); i++){
            System.debug('LIST ====> '+ListOfUpdateLicense[i]);
        }
        insert ListOfUpdateLicense;
        update personAccount;
    } 

   


    
}