force-app/main/default/objects/Account/fields/Broker_Contact__c.field-meta.xml
<CustomField>
    <fullName>Broker_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Broker who is managing the account</inlineHelpText>
    <label>Broker</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Brokerage</value>
        </filterItems>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Brokerage_Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Brokerage_Account__c.field-meta.xml
<CustomField>
    <fullName>Brokerage_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Brokerage firm who is managing the account</inlineHelpText>
    <label>Brokerage</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Brokerage</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Clients</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/HiddenAccount__c.field-meta.xml
<CustomField>
    <fullName>HiddenAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sponsored Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (HiddenAccount)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/IBC_Code__c.field-meta.xml
<CustomField>
    <fullName>IBC_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>IBC code of an account</inlineHelpText>
    <label>IBC Code</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Program_Audience__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>IBC Code</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Program_Audience__c</referenceTo>
    <relationshipLabel>Accounts (IBC Code)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Program_Audience__c.field-meta.xml
<CustomField>
    <fullName>Program_Audience__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Program Audience of an account.</inlineHelpText>
    <label>Program Type</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Program_Audience__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Program Type</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Program_Audience__c</referenceTo>
    <relationshipLabel>Sponsored Company</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Broker.recordType-meta.xml
<RecordType>
    <fullName>Broker</fullName>
    <active>true</active>
    <label>Broker</label>
</RecordType>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <description>This will hold information about the individual that can be sponsored company’s agents and clients of the Open Market Program.</description>
    <label>Person Account</label>
</RecordType>

force-app/main/default/objects/Program_Audience__c/Program_Audience__c.object-meta.xml
<CustomObject>
    <description>Used to capture Program Type and IBC Code</description>
    <label>Program Type/ IBC Code</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Type/ IBC Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Audience__c/fields/IBC_Code__c.field-meta.xml
<CustomField>
    <fullName>IBC_Code__c</fullName>
    <label>IBC Code</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/broker_contact__c.field-meta.xml
<CustomField>
    <fullName>broker_contact__c</fullName>
    <label>Broker Contact</label>
    <relationshipName>Users1</relationshipName>
    <restrictedAdminField>true</restrictedAdminField>
    <type>Hierarchy</type>
</CustomField>

force-app/main/default/classes/TestingClass.cls
@IsTest

public class TestingClass {
    
    
    static testMethod void test_PersonInfo(){
        
        
        
      //  UserRole r = new UserRole(name = 'TEST ROLE');
     //   Database.insert(r);
        
           
        Account brokerAccount = new Account();
        brokerAccount = TestDataFactory_SelfRegisterController.getBrokerAccount();
        Contact brokerCon = TestDataFactory_SelfRegisterController.getBroker(brokerAccount.Id);
        Program_Audience__c IbcObj = TestDataFactory_SelfRegisterController.getIBC();
        
        Account businessAccount = new Account();
        businessAccount = TestDataFactory_SelfRegisterController.getBusinessAcc('Bound', brokerAccount.Id, brokerCon.Id, IbcObj.Id);

        /*
        UserRole r = new UserRole(name = 'TEST ROLE');
        Database.insert(r);
        
        
        User userWithRole = new User(alias = 'hasrole', email='userwithrole@roletest.com', userroleid = r.id,
                                     emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US', 
                                     localesidkey='en_US', profileid = UserInfo.getProfileId(), 
                                     timezonesidkey='America/Los_Angeles', username='userwithrole@testorg.com');
       
        
        */
        Account a;
      //  System.runAs(userWithRole){
            String recordTypeId = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
            
            a = new Account(RecordTypeId = recordTypeId, 
                            FirstName = 'TestPersonAccountFirst', 
                            LastName = 'TestPersonAccountLast', 
                            PersonEmail = 'test@user.com',
                            Billingstreet = 'Mary street',
                            BillingCity = 'Toronto',
                            BillingCountry = 'Canada',
                            BillingPostalCode = 'M3T 63A',
                            BillingState = 'Ontario',
                            Brokerage_Account__c = brokerAccount.Id,
                            Broker_Contact__c = brokerCon.Id,
                            HiddenAccount__c = businessAccount.Id
                            );
            insert a;
        //}
        Account acc = [Select PersonContactId From Account Where Id = :a.Id];
        Profile p = [SELECT Id FROM Profile WHERE Name = 'Custom Customer Community' LIMIT 1];
        User u = new User(
            FirstName = 'TestFirstName',
            LastName = 'TestLastName',
            Email = 'test@user.com',
            Username = 'test@user.com',
            Alias = 'TestPA', 
            TimeZoneSidKey = 'GMT', 
            LocaleSidKey = 'en_US', 
            EmailEncodingKey = 'UTF-8', 
            ProfileId = p.Id, 
            LanguageLocaleKey = 'en_US',
            ContactId = acc.PersonContactId);
        
        insert u;
                
        test.startTest();
        System.runAs(u){
            PersonInformation.getAccountRecord();
        }
        test.stopTest();
        
        
        
        /* Program_Audience__c IbcObj = TestDataFactory_SelfRegisterController.getIBC();
Program_Audience__c ProgObj = TestDataFactory_SelfRegisterController.getProgramType();
System.debug('Program Audience::' + ProgObj);   



Account person = New Account();                       
person.PersonEmail = 'email@test.com';
person.IBC_Code__c = IbcObj.Id;
person.Program_Audience__c = ProgObj.Id;
person.LastName = 'Khan';
person.Billingstreet = 'Mary street';
person.BillingCity = 'Toronto';
person.BillingCountry = 'Canada';
person.BillingPostalCode = 'M3T 63A';
person.BillingState = 'Ontario';        
person.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
insert person;

system.debug('This is the account ID::::' + person.Id);
Account brokerAccount = new Account();
brokerAccount = TestDataFactory_SelfRegisterController.getBrokerAccount();

Contact brokerCon = TestDataFactory_SelfRegisterController.getBroker(brokerAccount.Id);

system.debug('This is the broker contact::::::' + brokerCon);
system.debug('This is personAccount  ' + person);
system.debug('This is IbcObj  ' + IbcObj);*/
        
        
        
        
        
        
        
        
        
        /* Profile p = [SELECT Id FROM Profile WHERE Name='Custom Customer Community'];
Contact contact = new Contact(LastName ='testCon',AccountId = person.Id);
insert contact;  
User u = new User(
Alias = 'standt', 
Email='baberCJA@cloudjunction.cloud',
UserName= 'baberCJA@cloudjunction.cloud',
LastName='CJA',
CommunityNickname = 'User16166802911282164072',
ProfileId = p.Id,
TimeZoneSidKey='America/Los_Angeles',
LocaleSidKey='en_US',
EmailEncodingKey='UTF-8',
LanguageLocaleKey='en_US',
ContactId = contact.Id
);
insert u; 

test.startTest();
System.runAs(u) {
system.debug('This is the user i have created:::'+ u );
PersonInformation.getAccountRecord();
}
test.stopTest();
}
}*/
        
    }
}