force-app/main/default/objects/Account/fields/Broker_Contact__c.field-meta.xml
<CustomField>
    <fullName>Broker_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Broker who is managing the account</inlineHelpText>
    <label>Broker</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Brokerage</value>
        </filterItems>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Brokerage_Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Brokerage_Account__c.field-meta.xml
<CustomField>
    <fullName>Brokerage_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Brokerage firm who is managing the account</inlineHelpText>
    <label>Brokerage</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Brokerage</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Clients</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Program_Audience__c.field-meta.xml
<CustomField>
    <fullName>Program_Audience__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Program Audience of an account.</inlineHelpText>
    <label>Program Type</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Program_Audience__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Program Type</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Program_Audience__c</referenceTo>
    <relationshipLabel>Sponsored Company</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Applicant_Response__c/Applicant_Response__c.object-meta.xml
<CustomObject>
    <description>Used to capture response of a question provided by an applicant</description>
    <label>Applicant Response</label>
    <nameField>
        <label>Applicant Answer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applicant Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Applicant_Response__c/fields/Program_Application__c.field-meta.xml
<CustomField>
    <fullName>Program_Application__c</fullName>
    <inlineHelpText>Applicant response on the program application</inlineHelpText>
    <label>Program Application</label>
    <referenceTo>Program_Application__c</referenceTo>
    <relationshipLabel>Applicant Responses</relationshipLabel>
    <relationshipName>Applicant_Responses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Applicant_Response__c/fields/Program_Question__c.field-meta.xml
<CustomField>
    <fullName>Program_Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Program question of which applicant has answered</inlineHelpText>
    <label>Program Question</label>
    <referenceTo>Program_Question__c</referenceTo>
    <relationshipLabel>Applicant Responses</relationshipLabel>
    <relationshipName>Question_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Applicant_Response__c/fields/Question_Answer__c.field-meta.xml
<CustomField>
    <fullName>Question_Answer__c</fullName>
    <label>Question Answer</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Broker__c.field-meta.xml
<CustomField>
    <fullName>Broker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Broker</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Broker</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Broker</relationshipLabel>
    <relationshipName>Contacts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_Application__c/Program_Application__c.object-meta.xml
<CustomObject>
    <label>Program Application</label>
    <nameField>
        <label>Program Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Application</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Application__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>A person account who applied for eligibility test</inlineHelpText>
    <label>Program Applicant</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Program Application</relationshipLabel>
    <relationshipName>Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_Application__c/fields/Broker__c.field-meta.xml
<CustomField>
    <fullName>Broker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Broker who is managing the application</inlineHelpText>
    <label>Broker</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Program Application</relationshipLabel>
    <relationshipName>Program_Application</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_Application__c/fields/Brokerage_Account__c.field-meta.xml
<CustomField>
    <fullName>Brokerage_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Brokerage firm who is managing the application</inlineHelpText>
    <label>Brokerage Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Program Application (Brokerage Account)</relationshipLabel>
    <relationshipName>Program_Application</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_Application__c/fields/Program_Audience__c.field-meta.xml
<CustomField>
    <fullName>Program_Audience__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Program Audience of an applicant who submitted the program application</inlineHelpText>
    <label>Program Type</label>
    <referenceTo>Program_Audience__c</referenceTo>
    <relationshipLabel>Program Application</relationshipLabel>
    <relationshipName>Program_Application</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_Application__c/fields/Reason_to_Application_Fail__c.field-meta.xml
<CustomField>
    <fullName>Reason_to_Application_Fail__c</fullName>
    <inlineHelpText>Applicant to provide additional details to verify his application if it rejected due to wrong answers.</inlineHelpText>
    <label>Reason to Application Fail</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Program_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Name to identify details of a program application</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Saved</fullName>
            </value>
            <value>
                <fullName>Approved with condition</fullName>
            </value>
            <value>
                <fullName>Approval workflow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program_Application__c/fields/Submission_Date__c.field-meta.xml
<CustomField>
    <fullName>Submission_Date__c</fullName>
    <inlineHelpText>Submission date of a program application</inlineHelpText>
    <label>Submission Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Program_Audience__c/Program_Audience__c.object-meta.xml
<CustomObject>
    <description>Used to capture Program Type and IBC Code</description>
    <label>Program Type/ IBC Code</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Type/ IBC Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Question__c/Program_Question__c.object-meta.xml
<CustomObject>
    <description>Used to capture question of a Program Type</description>
    <label>Program Question</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Program Question Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Question__c/fields/Correct_Answer__c.field-meta.xml
<CustomField>
    <fullName>Correct_Answer__c</fullName>
    <inlineHelpText>Correct answer of the question of a specific Program Type</inlineHelpText>
    <label>Correct Answer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Program_Question__c/fields/Program_Audience__c.field-meta.xml
<CustomField>
    <fullName>Program_Audience__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Audience</label>
    <referenceTo>Program_Audience__c</referenceTo>
    <relationshipLabel>Program Questions</relationshipLabel>
    <relationshipName>Program_Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_Question__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <inlineHelpText>Question of the Program Type</inlineHelpText>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Program Questions</relationshipLabel>
    <relationshipName>Program_Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{000}</displayFormat>
        <label>Question Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Question_Description__c.field-meta.xml
<CustomField>
    <fullName>Question_Description__c</fullName>
    <inlineHelpText>Stated the question</inlineHelpText>
    <label>Question Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>What is the type of question?</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Pick list</fullName>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EligibilityTest.cls
public without sharing class EligibilityTest {

public static Applicant_Response__c questions = new applicant_Response__c();

public static Account account = new Account();
public static Program_Application__c pApplication = new Program_Application__c();
public static List<Applicant_Response__c> ListofARtoInsert = New List <Applicant_Response__c>();

@AuraEnabled
public static List<ApplicantQuestionsResponses> getAllQuestions(){


    System.debug('Program Questions Page');
    account = PersonInformation.getAccountRecord();
    System.debug('Account ::' + account);
    System.debug('Program Audience::' + account.Program_Audience__c);

    List<Program_Question__c> listofPQues = [Select id, name ,  Question__c 
                                            ,Question__r.Question_Description__c
                                            ,Correct_Answer__c , Question__r.Type__c 
                                            from Program_Question__c where Program_Audience__c =: account.Program_Audience__c  ];

    System.debug('List og Program Questions::' + listofPQues);

    List<ApplicantQuestionsResponses> listofAppQuesResp = new List<ApplicantQuestionsResponses>();

    Map<Id, Applicant_Response__c> mapOfAppResponse = getMapOfAppResponse(account);

    System.debug('Map of Applicant Response::' + mapOfAppResponse);

    for(Program_Question__c proQues: listofPQues){

        Applicant_Response__c response = new Applicant_Response__c();
        
        if(mapOfAppResponse.get(proQues.Id)!=null){

            System.debug('Response of Question already exist::' + mapOfAppResponse.get(proQues.Id));

            response = mapOfAppResponse.get(proQues.Id);
        
        }

        else{

            System.debug('Response does not exist');

            response.Answer__c = 'None';

        }

        ApplicantQuestionsResponses appQuesResp = new ApplicantQuestionsResponses(proQues,response,proQues.Id);
      
        System.debug('App Question Response::' + appQuesResp);
        listofAppQuesResp.add(appQuesResp);

    }


        return listofAppQuesResp;
    
    }  

public static Map<Id, Applicant_Response__c> getMapOfAppResponse(Account account){

    Map<Id, Applicant_Response__c> mapOfAppResponse = new Map<Id, Applicant_Response__c>();

    if(getProgramApplication()!=null){

        List<Applicant_Response__c> listofAppResponse = [Select id, name , Answer__c, Program_Question__c, Program_Application__c, Question_Answer__c from Applicant_Response__c where Program_Application__c =: getProgramApplication().Id];

        System.debug('List of Applicant Responses::' + listofAppResponse);    

        for(Applicant_Response__c appResponse:listofAppResponse){

            System.debug('App Response::' + appResponse);
            mapOfAppResponse.put(appResponse.Program_Question__c , appResponse);

        }
    }
    
    return mapOfAppResponse;
}    

@AuraEnabled
public static Program_Application__c getProgramApplication(){

    account = PersonInformation.getAccountRecord();

    List<Program_Application__c> listofRelatedProgramApplication = [Select name, id from Program_Application__c where account__c =: account.Id LIMIT 1];
    
    System.debug('List of Related Program Application::' + listofRelatedProgramApplication);

    if(listofRelatedProgramApplication.size()>0){

        return listofRelatedProgramApplication[0];

    }

    return null;

}


@AuraEnabled
public static string saveCustomerResponse(Boolean EligibilityTest , String FailedReason, List<Applicant_Response__c> listOfAppQuesResp, Boolean isCreate ){

    System.debug('Application Answers:: ' + listOfAppQuesResp);
    System.debug('Program Questions Page');
    account = PersonInformation.getAccountRecord();
    System.debug('Account ::' + account);
    System.debug('Program Audience::' + account.Program_Audience__c);

    String ExecutionStatus = '';

    pApplication = new Program_Application__c();
    pApplication.Account__c = account.id;
    pApplication.Brokerage_Account__c = account.Brokerage_Account__c;
    pApplication.Broker__c = account.Broker_Contact__c;
    pApplication.Program_Audience__c = account.Program_Audience__c;
    pApplication.Submission_Date__c = System.Now();
    pApplication.Name = account.Name + '-' + account.Program_Audience__r.Name;
    pApplication.Id = listOfAppQuesResp[0].Program_Application__c;

    if(EligibilityTest){

        System.debug('Eligibility Status Set to Submitted');
        pApplication.Status__c = 'Submitted';
        pApplication.Reason_to_Application_Fail__c = FailedReason;

    }

    else{

        System.debug('Eligibility Status Set to Approved');
        pApplication.Status__c = 'Approved';

    }

    
    if(isCreate){

        System.debug('Application Status is false so create the Application');
        pApplication = createProgramApp(pApplication);

        System.debug('PApplication is created::' + pApplication);
        if(pApplication!=null){

            return createListofApplicantResponse(listOfAppQuesResp, pApplication);

        }

        return 'Program Application have not created , please contact support for further clarification';


    }
    else{


        pApplication.Id = getProgramApplication().Id;
        System.debug('Application to be Updated');
        pApplication = updateProgramApp(pApplication);
    
        System.debug('Application Status is false so create the Application');
        
        if(pApplication!=null){

            return updateListofApplicantResponse(listOfAppQuesResp, pApplication);

        }

        return 'Program Application have not created , please contact support for further clarification';
    }

        
    }
    
    
public static Program_Application__c createProgramApp(Program_Application__c pApplication){

    try{


        insert pApplication;
        System.debug('Program Application Created::' +pApplication);
        return pApplication;

    }
    catch(Exception e){

        System.debug(e.getMessage());
        
        return null;
    }

}


public static Program_Application__c updateProgramApp(Program_Application__c pApplication){

    try{

        update pApplication;
        System.debug('Program Application Updated::' +pApplication);
        return pApplication;

    }catch(Exception e){

        System.debug(e.getMessage());
        return null;


    }
    
}


public static String createListofApplicantResponse(List<Applicant_Response__c> ListAppResponse , Program_Application__c pApplication){

    try{
    
            insert setAppResponseList(ListAppResponse , pApplication);
            return null;
    }
    catch(Exception e){

        System.debug(e.getMessage());
        return e.getMessage();
        
    }


}


public static String updateListofApplicantResponse(List<Applicant_Response__c> ListAppResponse , Program_Application__c pApplication){

    try{

            
            update setAppResponseList(ListAppResponse , pApplication);
            return null;
    }
    catch(Exception e){

        System.debug(e.getMessage());
        return e.getMessage();
        
    }


}

public static List<Applicant_Response__c> setAppResponseList(List<Applicant_Response__c> ListAppResponse, Program_Application__c pApplication){

    
    for(Applicant_Response__c appQuesResp: ListAppResponse){

        system.debug('Application Question Response::' + appQuesResp); 
        appQuesResp.Program_Application__c = pApplication.Id;
    }

    return ListAppResponse;
}

public class ApplicantQuestionsResponses{

@AuraEnabled
public Program_Question__c programQuestion;
@AuraEnabled
public Applicant_Response__c response;
@AuraEnabled
public Id QuestionId;
    
ApplicantQuestionsResponses(Program_Question__c programQuestion,Applicant_Response__c response,Id QuestionId){

    this.programQuestion = programQuestion;
    this.response = response;
    this.QuestionId = QuestionId;

}


}   
}