force-app/main/default/objects/Account/fields/Broker_Contact__c.field-meta.xml
<CustomField>
    <fullName>Broker_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Broker who is managing the account</inlineHelpText>
    <label>Broker</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Brokerage</value>
        </filterItems>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Brokerage_Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Brokerage_Account__c.field-meta.xml
<CustomField>
    <fullName>Brokerage_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Brokerage firm who is managing the account</inlineHelpText>
    <label>Brokerage</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Brokerage</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Clients</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/HiddenAccount__c.field-meta.xml
<CustomField>
    <fullName>HiddenAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sponsored Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (HiddenAccount)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Program_Audience__c.field-meta.xml
<CustomField>
    <fullName>Program_Audience__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Program Audience of an account.</inlineHelpText>
    <label>Program Type</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Program_Audience__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Program Type</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Program_Audience__c</referenceTo>
    <relationshipLabel>Sponsored Company</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Username</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Program_Audience__c/Program_Audience__c.object-meta.xml
<CustomObject>
    <description>Used to capture Program Type and IBC Code</description>
    <label>Program Type/ IBC Code</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Type/ IBC Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User/fields/broker_contact__c.field-meta.xml
<CustomField>
    <fullName>broker_contact__c</fullName>
    <label>Broker Contact</label>
    <relationshipName>Users1</relationshipName>
    <restrictedAdminField>true</restrictedAdminField>
    <type>Hierarchy</type>
</CustomField>

.history/force-app/main/default/classes/SelfRegisterController_20200521093513.cls
global without sharing class SelfRegisterController {
   
    @AuraEnabled
    public static void saveAccountRecord(Account objAcc , String accId){
        

        System.debug('Account Record::' + objAcc);

        System.debug('Account FirstName::' + objAcc.lastname);
        System.debug('Account FirstName::' + objAcc.phone);

        System.debug('Account Username::' + objAcc.Username__c);
        System.debug('Account FirstName::' + objAcc.PersonEmail);
        System.debug('Account has the values::' + objAcc);
        
        

        try{
        
            Account  parentAccount = [Select name , id , program_audience__c , brokerage_account__c, Broker_Contact__c  from Account where id =: accId];

            // First Check the provided accId exist in Salesforce or not 

            objAcc.HiddenAccount__c = accId;
            objAcc.brokerage_account__c = parentAccount.brokerage_account__c;
            objAcc.Broker_Contact__c = parentAccount.Broker_Contact__c;
            objAcc.program_audience__c = parentAccount.program_audience__c;


            insert objAcc;

            System.debug('Account is inserted::' + objAcc);
            System.debug('Account Id::' + accId);
            
            Account perAcc = [Select id, firstname, lastname, PersonContactId from Account where id =: objAcc.Id];
            
            AccountContactRelation accConRel = new AccountContactRelation();
            accConRel.AccountId = accId;
            accConRel.ContactId = perAcc.PersonContactId;
            accConRel.Roles = 'Employee';
            accConRel.IsActive = TRUE;
            insert accConRel;
            
            Profile pro = [Select id , name from Profile where Id =: '00ef0000000KvVhAAK'];
           
            
            User usr = new User(LastName = objAcc.LastName,
                                FirstName=objAcc.FirstName,
                                Email = objAcc.PersonEmail,
                                Username = objAcc.Username__c,
                                ProfileId = pro.id,
                                TimeZoneSidKey = 'GMT',
                                LanguageLocaleKey = 'en_US',
                                EmailEncodingKey = 'UTF-8',
                                LocaleSidKey = 'en_US',
                                ContactId = perAcc.PersonContactId,
                                Alias = objAcc.LastName,
                                //PortalRole = 'COO',
                                CommunityNickname = objAcc.LastName
                               );
            
                // All your test code here
                insert usr;
            
            
            insert usr;
        }
        catch(Exception ex) {
            //throw new AuraHandledException(ex.getMessage());
            System.debug('Exception Error::' + ex.getMessage());
            
        }
    }
}