force-app/main/default/objects/Account/fields/Broker_Contact__c.field-meta.xml
<CustomField>
    <fullName>Broker_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Broker who is managing the account</inlineHelpText>
    <label>Broker</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Brokerage</value>
        </filterItems>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Brokerage_Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Brokerage_Account__c.field-meta.xml
<CustomField>
    <fullName>Brokerage_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Brokerage firm who is managing the account</inlineHelpText>
    <label>Brokerage</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Brokerage</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Clients</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/FinServ__Status__c.field-meta.xml
<CustomField>
    <fullName>FinServ__Status__c</fullName>
    <inlineHelpText>Current Status of an account. Prospect,Prospect,Submission, Quote, Bound, Closed</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Submission</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Bound</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Firm_Owner__c.field-meta.xml
<CustomField>
    <fullName>Firm_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Firm Owner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Firm Owner)</relationshipLabel>
    <relationshipName>Accounts2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/HiddenAccount__c.field-meta.xml
<CustomField>
    <fullName>HiddenAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sponsored Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (HiddenAccount)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/IBC_Code__c.field-meta.xml
<CustomField>
    <fullName>IBC_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>IBC code of an account</inlineHelpText>
    <label>IBC Code</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Program_Audience__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>IBC Code</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Program_Audience__c</referenceTo>
    <relationshipLabel>Accounts (IBC Code)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Program_Audience__c.field-meta.xml
<CustomField>
    <fullName>Program_Audience__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Program Audience of an account.</inlineHelpText>
    <label>Program Type</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Program_Audience__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Program Type</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Program_Audience__c</referenceTo>
    <relationshipLabel>Sponsored Company</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Brokerage.recordType-meta.xml
<RecordType>
    <fullName>Brokerage</fullName>
    <active>true</active>
    <description>This will hold information about the broker&apos;s company</description>
    <label>Brokerage</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Broker.recordType-meta.xml
<RecordType>
    <fullName>Broker</fullName>
    <active>true</active>
    <label>Broker</label>
</RecordType>

force-app/main/default/objects/Extended_Report_Period__c/Extended_Report_Period__c.object-meta.xml
<CustomObject>
    <description>Used to capture extended reporting period of Quote/Policy</description>
    <label>Extended Report Period</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Extended Report Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Extended_Report_Period__c/fields/Extended_Report_Period__c.field-meta.xml
<CustomField>
    <fullName>Extended_Report_Period__c</fullName>
    <inlineHelpText>What is the period of extended reporting ?</inlineHelpText>
    <label>Extended Report Period</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/Cancellation_Amount__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Amount__c</fullName>
    <inlineHelpText>Cancellation Amount of the Policy</inlineHelpText>
    <label>Cancellation Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/Extended_Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Extended_Reporting_Period__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>ERP purchased on policy</inlineHelpText>
    <label>Purchased ERP</label>
    <referenceTo>Extended_Report_Period__c</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/IBC_Code__c.field-meta.xml
<CustomField>
    <fullName>IBC_Code__c</fullName>
    <formula>NameInsured.IBC_Code__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>IBC Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Program_Audience__c/Program_Audience__c.object-meta.xml
<CustomObject>
    <description>Used to capture Program Type and IBC Code</description>
    <label>Program Type/ IBC Code</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Type/ IBC Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Audience__c/fields/IBC_Code__c.field-meta.xml
<CustomField>
    <fullName>IBC_Code__c</fullName>
    <label>IBC Code</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote2__c/Quote2__c.object-meta.xml
<CustomObject>
    <description>Quote is a bundle of different products with Policy Options and Product Coverages, customized specifically for each opportunity. This object will only be associated with Business companies. There can be multiple quotes associated with the opportunity, to track multiple quotes, there will be a status field which will have options like Draft, Activated, Rejected and only one quote can have ‘activated’ status under one opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote2__c/fields/Brokerage_Account__c.field-meta.xml
<CustomField>
    <fullName>Brokerage_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>brokerage firm who is managing the quote</inlineHelpText>
    <label>Brokerage</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Brokerage value does not exist or does not match filter criteria.</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Brokerage</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/broker_contact__c.field-meta.xml
<CustomField>
    <fullName>broker_contact__c</fullName>
    <label>Broker Contact</label>
    <relationshipName>Users1</relationshipName>
    <restrictedAdminField>true</restrictedAdminField>
    <type>Hierarchy</type>
</CustomField>

force-app/main/default/classes/TestPersonInformation.cls
@IsTest

public class TestPersonInformation {
    
    static testMethod void validateGetAccountRecord(){
        UserRole r = new UserRole(name = 'TEST ROLE');
        Database.insert(r);
        
        User userWithRole = new User(alias = 'hasrole', email='userwithrole@roletest.com', userroleid = r.id,
                                     emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US', 
                                     localesidkey='en_US', profileid = UserInfo.getProfileId(), IsActive = True,
                                     timezonesidkey='America/Los_Angeles', username='userwithrole@testorg.com');
        Account a;
        

        Profile p1 = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1];
        userWithRole.ProfileId =p1.id;
        
        System.runAs(userWithRole){
            
            Account BrokerageAccount = New Account();
            
            BrokerageAccount.Name = 'Test Brokerage Account';
            BrokerageAccount.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Brokerage').getRecordTypeId();       
            
            
            insert BrokerageAccount;
            
            Contact BrokerContact = New Contact();
            
            BrokerContact.FirstName = 'Test Broker';
            BrokerContact.LastName = 'Test Broker Contact';
            BrokerContact.AccountId = BrokerageAccount.Id;
            BrokerContact.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Broker').getRecordTypeId();       
            
            insert BrokerContact;
            
            Program_Audience__c progType = new Program_Audience__c();
            progType.name = 'programtest';
            progType.Active__c = True;
            progType.IBC_Code__c = 'TEST CODE IBC';
            progType.RecordTypeId =  Schema.SObjectType.Program_Audience__c.getRecordTypeInfosByName().get('Program Type').getRecordTypeId(); 
            insert progType;
            
            
            Account HiddenAccount = New Account();
            
            HiddenAccount.Name = 'Test Hiddent Account11';
            HiddenAccount.FinServ__Status__c = 'Quote';
            HiddenAccount.Brokerage_Account__c = BrokerageAccount.Id;
            HiddenAccount.Broker_Contact__c = BrokerContact.Id;
            HiddenAccount.Program_Audience__c = progType.Id;
            HiddenAccount.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business').getRecordTypeId();       
            insert HiddenAccount;
            
            system.debug('Hidden Account => ' + HiddenAccount);
            
            String recordTypeId = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
            a = new Account(RecordTypeId = recordTypeId,
                            FirstName = '222',
                            LastName = '1313',
                            PersonEmail = 'testemail'+Math.round(Math.random()*Math.pow(10, 7))+'@testemail.com',
                            //      HiddenAccount__c = BrokerageAccount.Id,
                            Brokerage_Account__c = BrokerageAccount.Id,
                            Broker_Contact__c = BrokerContact.Id
                           );
            insert a;
            
            Account account = [Select HiddenAccount__c from Account where Id =: a.Id];
            account.HiddenAccount__c = HiddenAccount.Id;
            Account.BillingState = '';
            Account.BillingCountry = '';
            update account;
        }
        
        Account acc = [Select Id,PersonContactId,IsCustomerPortal From Account Where Id = :a.Id];
        
        
        Profile p = [SELECT Id FROM Profile WHERE Name = 'Custom Customer Community' LIMIT 1];
        User u = new User(
            FirstName = 'TestFirstName22',
            LastName = 'TestLastName1212',
            Email = 'testemail'+Math.round(Math.random()*Math.pow(10, 7))+'@testemail.com',
            Username =  'testemail'+Math.round(Math.random()*Math.pow(10, 8))+'@testemai.com',
            Alias = 'al', 
            TimeZoneSidKey = 'GMT', 
            LocaleSidKey = 'en_US', 
            EmailEncodingKey = 'UTF-8', 
            ProfileId = p.Id, 
            LanguageLocaleKey = 'en_US',
            ContactId = acc.PersonContactId);
        insert u;
 
               
        String accName = 'Ariba Investment Inc.';
        String ShippingStreet = 'TestStreet';
        String ShippingCity = 'Toronto';
        String ShippingState = 'Ontario';
        String ShippingPostalCode = 'M6t 0K4';
        //accObj.Firm_Owner__c = person.id;
        String Mailingcity = 'Ohio';
        
        
        
        
        /*Product2 prod = TestDataFactory_SelfRegisterController.getProduct();
        Opportunity opp = TestDataFactory_SelfRegisterController.getOpp(acc.Id , prod.Id);
        Quote2__c quote = TestDataFactory_SelfRegisterController.getQuote(opp.id, prod.id, BrokerContact.id, BrokerageAccount.id, acc.id);
        
        InsurancePolicy policy = TestDataFactory_SelfRegisterController.getInsurancePolicy(acc.id, 'test policy', prod.id, opp.id, quote.id, opp.id, quote.id, acc.id, BrokerageAccount.id, BrokerContact.id, 'Requested Cancellation');
        
        Extended_Report_Period__c erp = TestDataFactory_SelfRegisterController.getErp(policy.id);
        
        policy.Extended_Reporting_Period__c = erp.id;
        update policy;
        
        
        
        
        integer cancelAmt =  Integer.valueOf(policy.Cancellation_Amount__c); */
        
        
        
        
        
 
        test.startTest();
        System.runAs(userWithRole) {
        try{
            //system.debug(acc);
            Account pAccount = PersonInformation.getAccountRecord();
            
            PersonInformation.createFirmAccount(accName, ShippingStreet, ShippingCity, ShippingState, ShippingPostalCode, pAccount.Broker_Contact__c, pAccount.Brokerage_Account__c, pAccount.Id);
            PersonInformation.updateFirmAccount(accName, ShippingStreet, Mailingcity, ShippingState, ShippingPostalCode, pAccount.Broker_Contact__c, pAccount.Brokerage_Account__c, pAccount.Id);
            PersonInformation.GetFirmAccount(pAccount.Id);
            PersonInformation.contactList(pAccount.Id);
            
            
          //  List<Account> personAcc  = [select id, Name, PersonContactId from Account where Id =: pAccount.Id limit 1];
           // AccountContactRelation acr = TestDataFactory_SelfRegisterController.getACR(pAccount.id, personAcc[0].PersonContactId);
           // insert acr; 
            
            Account BrokerageAccount = New Account();
            
            BrokerageAccount.Name = 'Test Brokerage Account';
            BrokerageAccount.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Brokerage').getRecordTypeId();      
            insert BrokerageAccount;
            
            Contact BrokerContact = New Contact();
            BrokerContact.FirstName = 'Test Broker';
            BrokerContact.LastName = 'Test Broker Contact';
            BrokerContact.AccountId = BrokerageAccount.Id;
            BrokerContact.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Broker').getRecordTypeId();       
            insert BrokerContact;
            
            Program_Audience__c Ibc = new Program_Audience__c(name = 'ibcTest');
            Ibc.Name = '0001';
            Ibc.RecordTypeId = Schema.SObjectType.Program_Audience__c.getRecordTypeInfosByName().get('IBC Code').getRecordTypeId(); 
            
            Account businessAcc = new Account();
            businessAcc.Name = 'testBusiness';
            businessAcc.Brokerage_Account__c = BrokerageAccount.id;
            businessAcc.FinServ__Status__c = 'Bound';
            businessAcc.IBC_Code__c = Ibc.Id;
            businessAcc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business').getRecordTypeId();
        
            insert businessAcc;
            Product2 prod = TestDataFactory_SelfRegisterController.getProduct();
            Opportunity opp = TestDataFactory_SelfRegisterController.getOpp(pAccount.id , prod.Id);
            Quote2__c quote = TestDataFactory_SelfRegisterController.getQuote(opp.id, prod.id, BrokerContact.id, BrokerageAccount.id, pAccount.id);
        
            InsurancePolicy policy = TestDataFactory_SelfRegisterController.getInsurancePolicy(pAccount.id, 'test policy', prod.id, opp.id, quote.id, opp.id, quote.id, businessAcc.id, BrokerageAccount.id, BrokerContact.id, 'Bound',acc.PersonContactId);
        
            Extended_Report_Period__c erp = TestDataFactory_SelfRegisterController.getErp(policy.id);
        
            policy.Extended_Reporting_Period__c = erp.id;
            //policy.OwnerId = userWithRole.id;
            
            //system.debug('user id'+userWithRole.id);
            update policy;
           
           
           
            PersonInformation.recallFirmCancellation(pAccount.id,acc.PersonContactId);
   
        	    
        }
        
        catch(exception e){
            
            //exceptionCaught = true;
            System.debug('this is exception'+e);
        	}
        } 
        test.stopTest();
        
        
        
    }
    
    
    
    
    static testMethod void validateSaveAccountRecord(){
        
        Boolean exceptionCaught = false;
        
        
        Account account = new account(LastName='Doe',FirstName='John');
        insert account;                
        
        test.startTest();
        try{
            PersonInformation.saveAccountRecord(account);
        }
        
        catch(exception e){
            
            exceptionCaught = true;
        }
        
        test.stopTest();
    }
    
    
    static testMethod void validateUpdateFirmAddress(){
        
        Boolean exceptionCaught = false;
        
        
        Account account = new account(LastName='Doe',FirstName='John');
        insert account;                
           
        //account.lastname = '';
        
        test.startTest();
        try{
            PersonInformation.updateFirmAddress(account);
        }
        
        catch(exception e){
            
            exceptionCaught = true;
        }
        
        test.stopTest();
    }
    
    //for validating methods : cancelpolicy() and cancelfirmpolicy
    static testmethod void validateCancelPolicy()
    {
        Account brokerage = TestDataFactory_SelfRegisterController.getBrokerAccount();
        Contact broker = TestDataFactory_SelfRegisterController.getBroker(brokerage.Id);
        Program_Audience__c ibc = TestDataFactory_SelfRegisterController.getIBC();
        Program_Audience__c testProg = TestDataFactory_SelfRegisterController.getProgramType();
        Account accObj = TestDataFactory_SelfRegisterController.getBusinessAcc('Bound', brokerage.Id, broker.Id, ibc.Id);
        Account person = TestDataFactory_SelfRegisterController.getPersonAcc('whatever@gmail.com', ibc.Id, testProg.id, 'test', accObj.id);
        List<Account> personAcc  = [select id, Name, PersonContactId from Account where Id =: person.Id limit 1];
        AccountContactRelation acr = TestDataFactory_SelfRegisterController.getACR(accObj.id, personAcc[0].PersonContactId);
        insert acr;
        
        Product2 prod = TestDataFactory_SelfRegisterController.getProduct();
        Opportunity opp = TestDataFactory_SelfRegisterController.getOpp(person.Id , prod.Id);
        Quote2__c quote = TestDataFactory_SelfRegisterController.getQuote(opp.id, prod.id, broker.id, brokerage.id, person.id);
        
        InsurancePolicy policy = TestDataFactory_SelfRegisterController.getInsurancePolicy(person.id, 'test policy', prod.id, opp.id, quote.id, opp.id, quote.id, accObj.id, brokerage.id, broker.id, 'Bound',personAcc[0].PersonContactId);
        
        Extended_Report_Period__c erp = TestDataFactory_SelfRegisterController.getErp(policy.id);
        
        policy.Extended_Reporting_Period__c = erp.id;
        update policy;
        
        //for validating cancelling firm policy
//InsurancePolicy policy2 = TestDataFactory_SelfRegisterController.getInsurancePolicy(person.id, 'test policy 2', prod.id, opp.id, quote.id, opp.id, quote.id, accObj.id, brokerage.id, broker.id, 'Bound',personAcc[0].PersonContactId);
       // policy.Extended_Reporting_Period__c = erp.id;
       // update policy2;
        
        
        
        integer cancelAmt =  Integer.valueOf(policy.Cancellation_Amount__c);  
         
        test.startTest();
        PersonInformation.cancelPolicy(person.id,personAcc[0].PersonContactId);
        PersonInformation.cancelFirmPolicy(person.id,personAcc[0].PersonContactId,cancelAmt);
       // PersonInformation.recallFirmCancellation(person.id,personAcc[0].PersonContactId);
        test.stopTest();
        
    }
    
   
    
    
    
    static testmethod void validateGetFirmAcc()
    {
        Account brokerage = TestDataFactory_SelfRegisterController.getBrokerAccount();
        Contact broker = TestDataFactory_SelfRegisterController.getBroker(brokerage.Id);
        test.startTest();
        PersonInformation.getBrokerageAccounts();
        test.stopTest();
    }
    
    
    
    
}