force-app/main/default/objects/Account/fields/HiddenAccount__c.field-meta.xml
<CustomField>
    <fullName>HiddenAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sponsored Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (HiddenAccount)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <description>This will hold information about the individual that can be sponsored company’s agents and clients of the Open Market Program.</description>
    <label>Person Account</label>
</RecordType>

force-app/main/default/objects/Policy_Option__c/Policy_Option__c.object-meta.xml
<CustomObject>
    <description>This object will store the information about the policy options available for all the agents/program participants of a sponsored/open market program. Each policy option will be tied to the Quote record. This object will also contain other information such as ‘Deductible’, confirmation of endorsements if added, and Estimated Annual Premium and Fees.</description>
    <label>Policy Option</label>
    <nameField>
        <label>Policy Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Option__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote2__c</referenceTo>
    <relationshipLabel>Policy Options</relationshipLabel>
    <relationshipName>Master_Policy_Options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy_Option__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <label>Activated</label>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote2__c/Quote2__c.object-meta.xml
<CustomObject>
    <description>Quote is a bundle of different products with Policy Options and Product Coverages, customized specifically for each opportunity. This object will only be associated with Business companies. There can be multiple quotes associated with the opportunity, to track multiple quotes, there will be a status field which will have options like Draft, Activated, Rejected and only one quote can have ‘activated’ status under one opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote2__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Account of a quote</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Master_Policies</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote2__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Quote&apos;s Current Status</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Quoted</fullName>
            </value>
            <value>
                <fullName>Activated</fullName>
                <label>Issued</label>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

.history/force-app/main/default/classes/CoverageChoice_20200304085054.cls
public class CoverageChoice {
    
    public static Account PersonAccount = new Account();
    

    //Combing all methods and list of policy options
    @AuraEnabled
    public static List <Policy_Option__c> getPOlst(){
        
        //Get Account Details of Running User
        PersonAccount = PersonInformation.getAccountRecord();
        
        //Get Activated Quote of Running User's Account 
        string QuoteId = getQuoteRecord(PersonAccount.HiddenAccount__c);
        
        //Get List of All Policy Options under Activated Quote
        List <Policy_Option__c> POLst = getPolicyOptions(QuoteId);
        
        return POLst;
    }
    
    
    public static string getQuoteRecord(string AccountId){
        try{
            Quote2__c QuoteRecord = [Select id from Quote2__c WHERE Account__c =: AccountId AND Recordtype.Name = 'Master Policy' AND Status__c = 'Activated' AND Expiration_Date__c <=  Today  LIMIT 1];
            return QuoteRecord.Id;        
        } 
        catch (exception e) {
            system.debug('Error:' + e.getMessage());
            return null;   
        }
        
    } 
    public static List<Policy_Option__c> getPolicyOptions(String QuoteId){
        try{   
            List <Policy_Option__c>  PolicyOptionslst  = [Select Id From Policy_Option__c Where Quote__c =: QuoteId];
            
            return PolicyOptionslst;
        }
        catch (exception e){
            system.debug('Error' + e.getMessage());
            return null;
        }
    }
    
}