force-app/main/default/objects/Account/fields/HiddenAccount__c.field-meta.xml
<CustomField>
    <fullName>HiddenAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sponsored Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (HiddenAccount)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Program_Audience__c.field-meta.xml
<CustomField>
    <fullName>Program_Audience__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Program Audience of an account.</inlineHelpText>
    <label>Program Type</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Program_Audience__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Program Type</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Program_Audience__c</referenceTo>
    <relationshipLabel>Sponsored Company</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_Audience__c/Program_Audience__c.object-meta.xml
<CustomObject>
    <description>Used to capture Program Type and IBC Code</description>
    <label>Program Type/ IBC Code</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Type/ IBC Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

.history/force-app/main/default/classes/PersonInformation_20200505061805.cls
public with sharing class PersonInformation {
    
    
    public static User usr = new User();

    public PersonInformation() {

    }

    @AuraEnabled
    public static Account getAccountRecord(){

        String usrId = UserInfo.getUserId();

        if(usrId!=null){

            usr = [Select id, Contact.AccountId, AccountId, ContactId from User where Id =: usrId];
        
            System.debug('User Information::' + usr);    

            if(Contact.AccountId!=null){

                Account usrAcc = [Select id, Program_Audience__c, Program_Audience__r.Name ,HiddenAccount__r.Name , HiddenAccount__c, personmailingstreet, PersonMailingCity, PersonMailingCountry, PersonMailingPostalCode, PersonMailingState, firstName, lastname, PersonEmail from Account where Id =: usr.Contact.AccountId LIMIT 1];
        
                System.debug('Account Information::' + usrAcc );    

                return usrAcc;

            }

            return null;
        }

        return null;

    }

    @AuraEnabled
    public static string saveAccountRecord(Account acc){


        try{

        update acc;
        return 'Account Updated Successfully';

        
        }
        catch(Exception e){

            System.debug(Logginglevel.ERROR, e.getMessage());
            throw new AuraHandledException(e.getMessage());
        }

        
    }
}