force-app/main/default/objects/Account/fields/Program_Audience__c.field-meta.xml
<CustomField>
    <fullName>Program_Audience__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Program Audience of an account.</inlineHelpText>
    <label>Program Type</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Program_Audience__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Program Type</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Program_Audience__c</referenceTo>
    <relationshipLabel>Sponsored Company</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_Application__c/Program_Application__c.object-meta.xml
<CustomObject>
    <label>Program Application</label>
    <nameField>
        <label>Program Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Application</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Application__c/fields/Program_Audience__c.field-meta.xml
<CustomField>
    <fullName>Program_Audience__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Program Audience of an applicant who submitted the program application</inlineHelpText>
    <label>Program Type</label>
    <referenceTo>Program_Audience__c</referenceTo>
    <relationshipLabel>Program Application</relationshipLabel>
    <relationshipName>Program_Application</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_Audience__c/Program_Audience__c.object-meta.xml
<CustomObject>
    <description>Used to capture Program Type and IBC Code</description>
    <label>Program Type/ IBC Code</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Type/ IBC Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Question__c/Program_Question__c.object-meta.xml
<CustomObject>
    <description>Used to capture question of a Program Type</description>
    <label>Program Question</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Program Question Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Question__c/fields/Correct_Answer__c.field-meta.xml
<CustomField>
    <fullName>Correct_Answer__c</fullName>
    <inlineHelpText>Correct answer of the question of a specific Program Type</inlineHelpText>
    <label>Correct Answer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Program_Question__c/fields/Program_Audience__c.field-meta.xml
<CustomField>
    <fullName>Program_Audience__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Audience</label>
    <referenceTo>Program_Audience__c</referenceTo>
    <relationshipLabel>Program Questions</relationshipLabel>
    <relationshipName>Program_Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_Question__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <inlineHelpText>Question of the Program Type</inlineHelpText>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Program Questions</relationshipLabel>
    <relationshipName>Program_Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{000}</displayFormat>
        <label>Question Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Question_Description__c.field-meta.xml
<CustomField>
    <fullName>Question_Description__c</fullName>
    <inlineHelpText>Stated the question</inlineHelpText>
    <label>Question Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>What is the type of question?</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Pick list</fullName>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

.history/force-app/main/default/classes/EligibilityTest_20200226034151.cls
public with sharing class EligibilityTest {
    
    
    public static Account account = new Account();
    public static Program_Application__c pApplication = new Program_Application__c();


    public EligibilityTest() {

        account = PersonInformation.getAccountRecord();
        
    }

    @AuraEnabled
    public static List<Program_Question__c> getAllQuestions(String pAudience){

        List<Program_Question__c> listofPQues = [Select id, name , Question__r.Question_Description__c , Correct_Answer__c , Question__r.Type__c from Program_Question__c where Program_Audience__c =: pAudience  ];

        return listofPQues;

    }

    public static createProgramApplication(){

        
    }


}