force-app/main/default/objects/Policy_Option__c/Policy_Option__c.object-meta.xml
<CustomObject>
    <description>This object will store the information about the policy options available for all the agents/program participants of a sponsored/open market program. Each policy option will be tied to the Quote record. This object will also contain other information such as ‘Deductible’, confirmation of endorsements if added, and Estimated Annual Premium and Fees.</description>
    <label>Policy Option</label>
    <nameField>
        <label>Policy Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Option__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote2__c</referenceTo>
    <relationshipLabel>Policy Options</relationshipLabel>
    <relationshipName>Master_Policy_Options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy_Option__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <label>Activated</label>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote_Product_Details__c/Quote_Product_Details__c.object-meta.xml
<CustomObject>
    <description>Used to capture coverage, extensions and sub-limit offered for a quote</description>
    <label>Quote Product Detail</label>
    <nameField>
        <label>Quote Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Product Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote_Product_Details__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Product Details</relationshipLabel>
    <relationshipName>Quote_Product_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote_Product_Details__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote2__c</referenceTo>
    <relationshipLabel>Quote Product Details</relationshipLabel>
    <relationshipName>Master_Policy_Coverage_Types</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quote_Product_Details__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Status of quote product</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Activated</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CreateQPDunderPOClass.cls
public class CreateQPDunderPOClass {
   /* 
    public static void getlistOfQuotePD(List<Policy_Option__c> listOfPolicyOption){
        
        Map<Id, List<Policy_Option__c>> PolicyOptionMap = getMapOfPolicyOption(listOfPolicyOption);
        List<Quote_Product__c> QPList = getListofQuote(PolicyOptionMap.keySet());
        Map<Id, List<Quote_Product__c>> QPMap = getMapOfQP(QPList);
        List<Quote_Product_Details__c> listOfQuotePD = getListOfQP(QPMap ,PolicyOptionMap );
               
        try{
            
            insert listOfQuotePD;
            
        } catch(Exception e){
            
            System.debug('Exception Message::' + e.getMessage());
        }
    }           

public static Map<Id, List<Policy_Option__c>> getMapOfPolicyOption (List<Policy_Option__c> listOfPolicyOption){
    
    Map<Id, List<Policy_Option__c>> PolicyOptionMap = new Map<Id, List<Policy_Option__c>>();
    List<Policy_Option__c> existingPolicyOption     = New List <Policy_Option__c>();
    List<Policy_Option__c> newPolicyOption          = New List <Policy_Option__c>();
    
    for (Policy_Option__c po : listOfPolicyOption){    
        
        If(po.Quote__c != Null) {
            
            If(PolicyOptionMap.containsKey(po.Quote__c)){
                existingPolicyOption = PolicyOptionMap.get(po.Quote__c);
                existingPolicyOption.add(po);
                PolicyOptionMap.put(po.Quote__c,existingPolicyOption);    
                
            }   
            
            else{
                newPolicyOption = New List <Policy_Option__c>();
                newPolicyOption.add(po);
                PolicyOptionMap.put(po.Quote__c,newPolicyOption);    
            }
        }
    }
    
    return PolicyOptionMap;
}

// List of Quote Products
public static List<Quote_Product__c> getListofQuote(Set<Id> setofPolicyOptionId){
    
    List<Quote_Product__c> QPList = [Select Name, id, Quote__c, Product__c, Product__r.Name  from Quote_Product__c where Quote__c IN:setofPolicyOptionId ];        
    return QPList;
    
}

// Get Map of QP
public static Map<Id, List<Quote_Product__c>> getMapOfQP(List<Quote_Product__c> QPList){
    
    Map<Id, List<Quote_Product__c>> QPMap = new Map<Id, List<Quote_Product__c>>();
    List<Quote_Product__c> existingQP     = New List <Quote_Product__c>();
    List<Quote_Product__c> newQP          = New List <Quote_Product__c>();  
    
    for (Quote_Product__c QP : QPList){
        
        If(QP.Quote__c != Null) {
            
            If(QPMap.containsKey(QP.Quote__c)){
                existingQP = QPMap.get(QP.Quote__c);
                existingQP.add(QP);
                QPMap.put(QP.Quote__c,existingQP);     
            }   
            
            else{
                newQP = New List <Quote_Product__c>();
                newQP.add(QP);
                QPMap.put(QP.Quote__c,newQP);          
                
            }
            
            System.debug('QPDList' + QPList);
            
        }
    }    
    
    return QPMap;
    
}    

// Get List of Quote Product Details
public static List<Quote_Product_Details__c> getListOfQP(Map<Id, List<Quote_Product__c>> QPMap , Map<Id, List<Policy_Option__c>> PolicyOptionMap){
    
    List<Quote_Product_Details__c> ListofQPDtoInsert = new List<Quote_Product_Details__c>();
    
    For (Id poId : PolicyOptionMap.keySet()){
        If(PolicyOptionMap.containsKey(poId)){
            For(Policy_option__c InsP : PolicyOptionMap.get(poId)){
                If(QPMap.containskey(poId)){
                    For(Quote_Product__c QPObj : QPMap.get(poId)){
                        
                        Quote_Product_Details__c QPD = New Quote_Product_Details__c();
                        QPD.Name                     = QPObj.Product__r.Name + '-' + Insp.Name;
                        QPD.Policy_Option__c         = Insp.Id;
                        QPD.Quote_Product__c         = QPObj.Id;
                        QPD.Quote__c                 = poId; 
                        QPD.Product__c               = QPObj.Product__c; 
                        QPD.Status__c                = 'Draft';
                        
                        ListofQPDtoInsert.add(QPD);
                        
                    }
                }
            }
        }
    }
    
    return ListofQPDtoInsert;
    
}*/
}