force-app/main/default/objects/Opportunity/fields/Broker__c.field-meta.xml
<CustomField>
    <fullName>Broker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Broker who is managing the opportunity</inlineHelpText>
    <label>Broker</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Account.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Brokerage__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Broker Contact)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Brokerage__c.field-meta.xml
<CustomField>
    <fullName>Brokerage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Brokerage firm who is managing an opportunity</inlineHelpText>
    <label>Brokerage</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Brokerage</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Referred Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Commission__c.field-meta.xml
<CustomField>
    <fullName>Commission__c</fullName>
    <inlineHelpText>Commission percentage for a brokerage</inlineHelpText>
    <label>Commission</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Discount_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Discount_Percentage__c</fullName>
    <inlineHelpText>Applicable discount on a policy premium</inlineHelpText>
    <label>Discount Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Master_Policy_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Master_Policy_Agreement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Quote of a renewal opportunity</inlineHelpText>
    <label>Quote</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Quote2__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Quote2__c</referenceTo>
    <relationshipLabel>Renewal Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Policy of a renewal opportunity</inlineHelpText>
    <label>Policy</label>
    <referenceTo>InsurancePolicy</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Premium_Amount__c.field-meta.xml
<CustomField>
    <fullName>Premium_Amount__c</fullName>
    <inlineHelpText>Basic premium amount of a policy</inlineHelpText>
    <label>Authorized Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product lookup</description>
    <inlineHelpText>Product lookup</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Transaction_Fees__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Fees__c</fullName>
    <inlineHelpText>Fixed transaction fees to be charged from customer</inlineHelpText>
    <label>Transaction Fees</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Certificate Cancellation</fullName>
                <label>Policy Cancellation</label>
            </value>
            <value>
                <fullName>Firm Rider Certificate Cancellation</fullName>
            </value>
            <value>
                <fullName>Mid-Term Change</fullName>
            </value>
            <value>
                <fullName>New Certificate</fullName>
            </value>
            <value>
                <fullName>Purchase ERP</fullName>
            </value>
            <value>
                <fullName>Renew Certificate</fullName>
                <label>Policy Renewal</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program_Application__c/Program_Application__c.object-meta.xml
<CustomObject>
    <label>Program Application</label>
    <nameField>
        <label>Program Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Application</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Application__c/fields/Broker__c.field-meta.xml
<CustomField>
    <fullName>Broker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Broker who is managing the application</inlineHelpText>
    <label>Broker</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Program Application</relationshipLabel>
    <relationshipName>Program_Application</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/createRenewalOpportunity.cls
public without sharing class createRenewalOpportunity {

    @AuraEnabled
    public static Opportunity createERPOpp (string name,string broker, string brokerage, string accountid,string productId,string policyId, string quoteId){
        
        system.debug('entering in method');
        
        Opportunity opp = new Opportunity ();
           
        system.debug('in opp instance');
        
            opp.Name  = name;
        	opp.StageName    = 'Qualification';
        	opp.CloseDate    = date.today();
        	opp.recordTypeId = '012f0000000guBwAAI';
        	opp.Broker__c    = broker;
        	opp.Brokerage__c = brokerage;
        	opp.AccountId    = accountid;
        	opp.Product__c   = productId;
        	opp.Policy__c    = policyId;
        	opp.Master_Policy_Agreement__c     = quoteId;
        	opp.Transaction_Type__c = 'Purchase ERP';
        	
        	//opp.OwnerId = '2F0056g0000023VYD';
        
        try{
            insert opp;
            system.debug('opp inserted: ' + opp );
            
        }
        catch(Exception e){
            
            System.debug(Logginglevel.ERROR, e.getMessage());
            throw new AuraHandledException(e.getMessage());
        }  
        system.debug('return opp :' + opp);
        return opp;
        
    } 
    
    @AuraEnabled
  public static Opportunity OppWhenPaymentSuccess(OppWrapper oppObj){
        
       Opportunity opp =  getOppInstance(oppObj);
      
      if(opp != null){
      
        try{
            insert opp;
            system.debug('opportunity inserted against transaction type'+ opp.Transaction_Type__c + '=>' + opp );
            
        }
        catch(Exception e){
            
            System.debug(Logginglevel.ERROR, e.getMessage());
            throw new AuraHandledException(e.getMessage());
        } 
      }
        system.debug('return opp :' + opp);
        return opp;
        
    }
    
    public static Opportunity getOppInstance(OppWrapper opportunityWrapper){
        
        Id OppRecTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get(opportunityWrapper.recordtypeDevName).getRecordTypeId();

        Opportunity opp = New Opportunity();
        
        opp.Name = opportunityWrapper.name;
        opp.StageName    = opportunityWrapper.stage;
        opp.Closedate    = date.today();
        opp.RecordTypeId = OppRecTypeId;
        opp.AccountId  = opportunityWrapper.accountid;
        opp.Type      = opportunityWrapper.type;
        opp.Policy__c = opportunityWrapper.policyId;
        opp.Product__c = opportunityWrapper.productId;
        //opp.Master_Policy_Agreement__c = opportunityWrapper.quoteId;
        opp.Broker__c = opportunityWrapper.broker;
        opp.Brokerage__c = opportunityWrapper.brokerage;
        opp.Commission__c = opportunityWrapper.commission;
        opp.Premium_Amount__c   = opportunityWrapper.amount;
        opp.Discount_Percentage__c = opportunityWrapper.discount;
        opp.Transaction_Fees__c = opportunityWrapper.policyfee;
        opp.CurrencyIsoCode = opportunityWrapper.curr;
        opp.transaction_type__c = opportunityWrapper.transactiontype;

        System.debug('Opportunity ::' + opp);
        return opp;        
    }
    
    public class OppWrapper{
        
        @AuraEnabled
        public string name {get;set;}
       	@AuraEnabled
        public string recordtypeDevName {get;set;}
        @AuraEnabled
        public string accountid {get;set;}
        @AuraEnabled
        public string type {get;set;}
        @AuraEnabled
        public string policyId {get;set;}
        @AuraEnabled
        public string productId {get;set;}
        @AuraEnabled
        public string quoteId {get;set;}
        @AuraEnabled
        public string broker {get;set;}
        @AuraEnabled
        public string brokerage {get;set;}
        @AuraEnabled
        public decimal commission {get;set;}
        @AuraEnabled
        public decimal amount {get;set;}
        @AuraEnabled
        public decimal discount {get;set;}
        @AuraEnabled
        public decimal policyfee {get;set;}
        @AuraEnabled
        public string curr {get;set;}
        @AuraEnabled
        public string stage {get;set;}
        @AuraEnabled
        public date closedate {get;set;}
        @AuraEnabled
        public string transactiontype {get;set;}
        
    }
    
    
    
       @AuraEnabled
    public static Opportunity updateOpportunity (string oppId, String stage){
        
         Opportunity OppList = [select id,StageName from Opportunity Where Id =: oppId ]; //AND Is_Firm_Insurance__c = True
           
        OppList.StageName = 'Closed Won';

            
        try{
            update OppList;
                        
        }
        catch(Exception e){
            
            System.debug(Logginglevel.ERROR, e.getMessage());
            throw new AuraHandledException(e.getMessage());
        }  
      
        return OppList;
        
    } 
    
     @AuraEnabled
    public static Opportunity updateOppAfterPaymentErr (string oppId){
        
         Opportunity OpList = [select id,StageName from Opportunity Where Id =: oppId ]; 
           
        OpList.StageName = 'Closed Lost';

            
        try{
            update OpList;
                        
        }
        catch(Exception e){
            
            System.debug(Logginglevel.ERROR, e.getMessage());
            throw new AuraHandledException(e.getMessage());
        }  
      
        return OpList;
        
    } 
    
    
      @AuraEnabled
    public static String deleteOpportunity (string accountId){
        
     List<Opportunity> OpList = [select id,Policy__c,Transaction_Type__c,isClosed  from Opportunity Where AccountId =: accountId
                              AND Transaction_Type__c = 'Purchase ERP' AND isClosed != True]; 

          if(OpList.size()>0){               
          delete OpList;
          return 'Opportunity Deleted';
          }
          
          else{
              
          return null; 
              
       }
    
       }    
   
     @AuraEnabled
     public static Program_Application__c createPolicy (Program_Application__c policy){
     
         System.debug('Policy::' + policy);
         insert policy;
         
         System.debug('Policy After Creation' + policy);
         
         return policy;
     }
}