force-app/main/default/objects/InsurancePolicy/fields/Broker__c.field-meta.xml
<CustomField>
    <fullName>Broker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Broker who is managing the policy</inlineHelpText>
    <label>Broker Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/Brokerage__c.field-meta.xml
<CustomField>
    <fullName>Brokerage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Brokerage firm who is managing the policy</inlineHelpText>
    <label>Brokerage</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Brokerage</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Referred Policies</relationshipLabel>
    <relationshipName>Insurance_Policies1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/Cancellation_Amount__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Amount__c</fullName>
    <inlineHelpText>Cancellation Amount of the Policy</inlineHelpText>
    <label>Cancellation Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/Days__c.field-meta.xml
<CustomField>
    <fullName>Days__c</fullName>
    <description>Days between policy effective date and policy cancellation date.</description>
    <formula>TODAY() -   DATEVALUE(EffectiveDate)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Days between policy effective date and policy cancellation date.</inlineHelpText>
    <label>Active Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/Master_Policy_Number__c.field-meta.xml
<CustomField>
    <fullName>Master_Policy_Number__c</fullName>
    <inlineHelpText>Master Policy Number of an Insurance Certificate</inlineHelpText>
    <label>Master Policy Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Broker__c.field-meta.xml
<CustomField>
    <fullName>Broker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Broker who is managing the opportunity</inlineHelpText>
    <label>Broker</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Account.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Brokerage__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Broker Contact)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Brokerage__c.field-meta.xml
<CustomField>
    <fullName>Brokerage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Brokerage firm who is managing an opportunity</inlineHelpText>
    <label>Brokerage</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Brokerage</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Referred Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Master_Policy_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Master_Policy_Agreement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Quote of a renewal opportunity</inlineHelpText>
    <label>Quote</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Quote2__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Quote2__c</referenceTo>
    <relationshipLabel>Renewal Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Policy of a renewal opportunity</inlineHelpText>
    <label>Policy</label>
    <referenceTo>InsurancePolicy</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Premium_Amount__c.field-meta.xml
<CustomField>
    <fullName>Premium_Amount__c</fullName>
    <inlineHelpText>Basic premium amount of a policy</inlineHelpText>
    <label>Authorized Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product lookup</description>
    <inlineHelpText>Product lookup</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Renewal_Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Renewal_Opportunity</fullName>
    <active>true</active>
    <businessProcess>FinServ__Opportunity Process</businessProcess>
    <description>To store information of Renewal occurs for a Master Policy Agreement.</description>
    <label>Renewal Opportunity</label>
</RecordType>

force-app/main/default/objects/Short_Rate__mdt/Short_Rate__mdt.object-meta.xml
<CustomObject>
    <label>Short Rate Cancellation</label>
    <pluralLabel>Short Rate Cancellations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Short_Rate__mdt/fields/Days_Policy_In_Force__c.field-meta.xml
<CustomField>
    <fullName>Days_Policy_In_Force__c</fullName>
    <label>Days Policy In Force</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Short_Rate__mdt/fields/Percentage_of_Premium_Retained__c.field-meta.xml
<CustomField>
    <fullName>Percentage_of_Premium_Retained__c</fullName>
    <label>Percentage of Premium Retained</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/CancelPolicy_ShortRate_Calculation.cls
public with sharing class CancelPolicy_ShortRate_Calculation {
    @InvocableMethod(label='CancelPolicy_ShortRate_Calculation')
    public static void execute(List<InsurancePolicy> policy) {
        
        Set <Decimal> DaysOfPolicy = new Set <Decimal>();
        
        for(Integer i = 0; i<policy.size(); i++)
        {
            DaysOfPolicy.add((Integer)policy[i].Days__c);
        }
        System.debug(DaysOfPolicy);
        
        Short_Rate__mdt[] shortRate = 
            [Select Days_Policy_In_Force__c,Percentage_of_Premium_Retained__c from Short_Rate__mdt where Days_Policy_In_Force__c in :DaysOfPolicy];
        System.debug(shortRate);
        List <RecordType> RecordTypeID_for_RenewalOpp =  [SELECT Id FROM RecordType WHERE SObjectType = 'Opportunity' and DeveloperName= 'Renewal_Opportunity'];
        
        System.debug('List of Policies '+policy);
        Map<decimal, decimal> SortRateData = new Map<decimal, decimal>();
        List <Opportunity> arrayOfOpportunities = new List<Opportunity>();
        for(Short_Rate__mdt record:shortRate)
        {
            SortRateData.put(record.Days_Policy_In_Force__c,record.Percentage_of_Premium_Retained__c);
            
        } 
        for (integer i = 0; i < policy.size() ; i++){
            decimal Percent_days = SortRateData.get((integer)policy[i].Days__c);
             
            Opportunity opp = new Opportunity();
            opp.CloseDate=date.today();
            opp.Name='Cancel Policy - ShortRate - '+policy[i].PolicyName;
            opp.StageName='Qualification';
            opp.AccountId = policy[i].NameInsuredId;
            opp.Broker__c = policy[i].Broker__c;
            opp.Brokerage__c = policy[i].Brokerage__c;
            opp.CurrencyIsoCode = policy[i].CurrencyIsoCode;
            //opp.Master_Policy_Agreement__c = policy[0].Master_Policy_Number__c;
            opp.Policy__c = policy[i].Id;
            opp.Product__c = policy[i].ProductId;
            opp.Premium_Amount__c = Percent_days*policy[i].PremiumAmount;
            policy[i].Cancellation_Amount__c = opp.Premium_Amount__c;
            opp.RecordTypeId= RecordTypeID_for_RenewalOpp[0].Id;
            opp.Type = 'Non Program';
            arrayOfOpportunities.add(opp);
            
            //insert opp;
        }
        system.debug(arrayOfOpportunities);
        insert arrayOfOpportunities;
        update policy;
        
        
    }
}