force-app/main/default/objects/InsurancePolicy/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <inlineHelpText>Category of insurance certificate</inlineHelpText>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Individual Insurance Certificate</fullName>
            </value>
            <value>
                <fullName>Firm Rider Insurance Certificate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/Policy_Option__c.field-meta.xml
<CustomField>
    <fullName>Policy_Option__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Policy Option</label>
    <referenceTo>Policy_Option__c</referenceTo>
    <relationshipLabel>Insurance Policies</relationshipLabel>
    <relationshipName>Insurance_Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Quote from where policy originated.</inlineHelpText>
    <label>Source Quote</label>
    <referenceTo>Quote2__c</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Policy Coverages</relationshipLabel>
    <relationshipName>Policy_Coverages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Product_Detail__c.field-meta.xml
<CustomField>
    <fullName>Product_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Detail</label>
    <referenceTo>ProductCoverage</referenceTo>
    <relationshipLabel>Policy Product Details</relationshipLabel>
    <relationshipName>Policy_Product_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy_Option__c/Policy_Option__c.object-meta.xml
<CustomObject>
    <description>This object will store the information about the policy options available for all the agents/program participants of a sponsored/open market program. Each policy option will be tied to the Quote record. This object will also contain other information such as ‘Deductible’, confirmation of endorsements if added, and Estimated Annual Premium and Fees.</description>
    <label>Policy Option</label>
    <nameField>
        <label>Policy Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Option__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote2__c</referenceTo>
    <relationshipLabel>Policy Options</relationshipLabel>
    <relationshipName>Master_Policy_Options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ProductCoverage/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Coverage</fullName>
            </value>
            <value>
                <fullName>Sub-limit</fullName>
            </value>
            <value>
                <fullName>Extensions</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProductCoverage/fields/Deductible_Amount__c.field-meta.xml
<CustomField>
    <fullName>Deductible_Amount__c</fullName>
    <label>Deductible Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote_Product_Details__c/Quote_Product_Details__c.object-meta.xml
<CustomObject>
    <description>Used to capture coverage, extensions and sub-limit offered for a quote</description>
    <label>Quote Product Detail</label>
    <nameField>
        <label>Quote Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Product Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote_Product_Details__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <inlineHelpText>Category of quote product detail</inlineHelpText>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Coverage</fullName>
            </value>
            <value>
                <fullName>Sub-limit</fullName>
            </value>
            <value>
                <fullName>Extension</fullName>
            </value>
            <value>
                <fullName>Endorsement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote_Product_Details__c/fields/Category_Group__c.field-meta.xml
<CustomField>
    <fullName>Category_Group__c</fullName>
    <label>Category Group</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Liability</fullName>
            </value>
            <value>
                <fullName>Uninsured Motorist Insurance</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Auto</fullName>
            </value>
            <value>
                <fullName>General</fullName>
            </value>
            <value>
                <fullName>Additional Coverage</fullName>
            </value>
            <value>
                <fullName>Section-1 Property Coverage</fullName>
            </value>
            <value>
                <fullName>Section 2/Liability Coverage</fullName>
            </value>
            <value>
                <fullName>Forms and Endorsements</fullName>
            </value>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Bundled Coverage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote_Product_Details__c/fields/Category_Group_Type__c.field-meta.xml
<CustomField>
    <fullName>Category_Group_Type__c</fullName>
    <label>Category Group Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bodily Injured</fullName>
            </value>
            <value>
                <fullName>Property Damage</fullName>
            </value>
            <value>
                <fullName>Medical Payments</fullName>
            </value>
            <value>
                <fullName>Collision</fullName>
            </value>
            <value>
                <fullName>Comprehensive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote_Product_Details__c/fields/Category_Group_Type_Value__c.field-meta.xml
<CustomField>
    <fullName>Category_Group_Type_Value__c</fullName>
    <label>Category Group Type Value</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Amount Per Person</fullName>
            </value>
            <value>
                <fullName>Amount Per Occurrence</fullName>
            </value>
            <value>
                <fullName>Actual Cash Value</fullName>
            </value>
            <value>
                <fullName>Duration</fullName>
            </value>
            <value>
                <fullName>Percentage</fullName>
            </value>
            <value>
                <fullName>Age</fullName>
            </value>
            <value>
                <fullName>Amount</fullName>
            </value>
            <value>
                <fullName>Range</fullName>
            </value>
            <value>
                <fullName>Boolean</fullName>
            </value>
            <value>
                <fullName>Pct</fullName>
            </value>
            <value>
                <fullName>Benefit for Lifetime</fullName>
            </value>
            <value>
                <fullName>Benefit to Age</fullName>
            </value>
            <value>
                <fullName>Benefit to Specific period</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote_Product_Details__c/fields/Coverage_Type_Description__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Type_Description__c</fullName>
    <label>Coverage Type Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quote_Product_Details__c/fields/Deductible_Amount__c.field-meta.xml
<CustomField>
    <fullName>Deductible_Amount__c</fullName>
    <inlineHelpText>Deductible amount applied on a policy product detail</inlineHelpText>
    <label>Deductible Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote_Product_Details__c/fields/Limit_Amount__c.field-meta.xml
<CustomField>
    <fullName>Limit_Amount__c</fullName>
    <label>Limit Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote_Product_Details__c/fields/Limit_Date__c.field-meta.xml
<CustomField>
    <fullName>Limit_Date__c</fullName>
    <label>Limit Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote_Product_Details__c/fields/Limit_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Limit_Percentage__c</fullName>
    <inlineHelpText>Sub-Limit percentage applied on policy product detail</inlineHelpText>
    <label>Sub-Limit Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quote_Product_Details__c/fields/Limit_Range__c.field-meta.xml
<CustomField>
    <fullName>Limit_Range__c</fullName>
    <label>Limit Range</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>15/30/5</fullName>
            </value>
            <value>
                <fullName>25/50/25</fullName>
            </value>
            <value>
                <fullName>50/100/50</fullName>
            </value>
            <value>
                <fullName>100/200/50</fullName>
            </value>
            <value>
                <fullName>200/500/100</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote_Product_Details__c/fields/Premium_Amount__c.field-meta.xml
<CustomField>
    <fullName>Premium_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Premium Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote_Product_Details__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Product Details</relationshipLabel>
    <relationshipName>Quote_Product_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote_Product_Details__c/fields/Product_Detail__c.field-meta.xml
<CustomField>
    <fullName>Product_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Detail</label>
    <referenceTo>ProductCoverage</referenceTo>
    <relationshipLabel>Quote Product Details</relationshipLabel>
    <relationshipName>Quote_Product_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote_Product_Details__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote2__c</referenceTo>
    <relationshipLabel>Quote Product Details</relationshipLabel>
    <relationshipName>Master_Policy_Coverage_Types</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/PolicyCoverageClass.cls
public class PolicyCoverageClass {
    
    
    /*public static List<InsurancePolicyCoverage> getListofIP(List<InsurancePolicy> listOfPolicy){
        
        Map<Id, List<InsurancePolicy>> PolicyMap = getMapOfPolicy(listOfPolicy);
        List<Quote_Product_Details__c> QPDList = getListofQuote(PolicyMap.keySet());
        Map<Id, List<Quote_Product_Details__c>> QPDMap = getMapOfQPD(QPDList);
        List<InsurancePolicyCoverage> listOfIIp = getListOfPPD(QPDMap ,PolicyMap );
        
        return listOfIIp;
    }
    
    // Get Map of Policy from the List of Policy with key Policy Option
    public static Map<Id, List<InsurancePolicy>> getMapOfPolicy (List<InsurancePolicy> listOfPolicy){
        
        Map<Id, List<InsurancePolicy>> PolicyMap = new Map<Id, List<InsurancePolicy>>();
        List<InsurancePolicy> existingPO = New List <InsurancePolicy>();
        List<InsurancePolicy> newPO = New List <InsurancePolicy>();
        
        for (InsurancePolicy ip : listOfPolicy){    
            
            If(ip.Policy_Option__c != Null) {
                
                If(PolicyMap.containsKey(ip.Policy_Option__c)){
                    existingPO = PolicyMap.get(ip.Policy_Option__c);
                    existingPO.add(ip);
                    PolicyMap.put(ip.Policy_Option__c,existingPO);    
                    
                }   
                
                else{
                    newPO = New List <InsurancePolicy>();
                    newPO.add(ip);
                    PolicyMap.put(ip.Policy_Option__c,newPO);    
                }
            }
        }
        
        return PolicyMap;
    }
    
    // Get List of QPD
    public static List<Quote_Product_Details__c> getListofQuote(Set<Id> setofPolicyId){
        
        List<Quote_Product_Details__c> QPDList = [Select id, Product_Detail__r.ProductId,name, Policy_Option__c,Category__c, Category_Code__c,
                                                            Category_Group__c, Category_Group_Type__c, Category_Group_Type_Value__c, Coverage_Code__c,
                                                            Coverage_Type_Description__c, Deductible_Amount__c, Effective_Date__c, Expiration_Date__c,
                                                            Limit_Amount__c, Limit_Date__c, Limit_Percentage__c, Limit_Range__c, Premium_Amount__c,
                                                            Product_Detail__c, Quote__c, Quote_Product__c
                                                  from Quote_Product_Details__c where Policy_Option__c IN:setofPolicyId];
        
        return QPDList;
    }
    
    // Get Map of QPD
    public static Map<Id, List<Quote_Product_Details__c>> getMapOfQPD(List<Quote_Product_Details__c> QPDList){
        
        Map<Id, List<Quote_Product_Details__c>> QPDMap = new Map<Id, List<Quote_Product_Details__c>>();
        List<Quote_Product_Details__c> existingQPD = New List <Quote_Product_Details__c>();
        List<Quote_Product_Details__c> newQPD = New List <Quote_Product_Details__c>();  
        
        for (Quote_Product_Details__c QPD : QPDList){
            
            If(QPD.Policy_Option__c != Null) {
                
                If(QPDMap.containsKey(QPD.Policy_Option__c)){
                    existingQPD = QPDMap.get(QPD.Policy_Option__c);
                    existingQPD.add(QPD);
                    QPDMap.put(QPD.Policy_Option__c,existingQPD);     
                }   
                
                else{
                    newQPD = New List <Quote_Product_Details__c>();
                    newQPD.add(QPD);
                    QPDMap.put(QPD.Policy_Option__c,newQPD);          
                    
                }
                
                System.debug('QPDList' + QPDList);
                
            }
        }    
        
        return QPDMap;
        
    }    
    
    // Get List of Policy Product Details
    public static List<InsurancePolicyCoverage> getListOfPPD(Map<Id, List<Quote_Product_Details__c>> QPDMap , Map<Id, List<InsurancePolicy>> PolicyMap ){
        
        List<InsurancePolicyCoverage> ListofQPDtoInsert = new List<InsurancePolicyCoverage>();
        
        For (Id poId : PolicyMap.keySet()){
            If(PolicyMap.containsKey(poId)){
                For(InsurancePolicy InsP : PolicyMap.get(poId)){
                    If(QPDMap.containskey(poId)){
                        For(Quote_Product_Details__c QPDObj : QPDMap.get(poId)){

                            InsurancePolicyCoverage PPD = New InsurancePolicyCoverage();
                            PPD.CoverageName      = QPDObj.Name;
                            PPD.InsurancePolicyId = InsP.Id;
                            PPD.Product__c        = QPDObj.Product_Detail__r.ProductId;
                            PPD.Category          = QPDObj.Category__c;
                            PPD.CategoryCode      = QPDObj.Category_Code__c;
                            PPD.CategoryGroup     = QPDObj.Category_Group__c;
                            PPD.CategoryGroupType = QPDObj.Category_Group_Type__c;
                            PPD.LimitRange        = QPDObj.Limit_Range__c;
                            PPD.LimitAmount       = QPDObj.Limit_Amount__c;
                            PPD.LimitPercentage   = QPDObj.Limit_Percentage__c;
                            PPD.LimitDate         = QPDObj.Limit_Date__c;
                            PPD.EffectiveDate     = QPDObj.Effective_Date__c;
                            PPD.ExpirationDate    = QPDObj.Expiration_Date__c;
                            PPD.PremiumAmount     = QPDObj.Premium_Amount__c;
                            PPD.DeductibleAmount  = QPDObj.Deductible_Amount__c;
                            PPD.Description       = QPDObj.Coverage_Type_Description__c;
                            
                            ListofQPDtoInsert.add(PPD);
                            
                        }
                    }
                }
            }        
        }    
        
        
        return ListofQPDtoInsert;
        
    }
  */  
}