force-app/main/default/objects/InsurancePolicy/fields/Policy_Holder__c.field-meta.xml
<CustomField>
    <fullName>Policy_Holder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Policy Holder of the policy</inlineHelpText>
    <label>Policy Holder</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Insurance Policies (Policy Holder)</relationshipLabel>
    <relationshipName>Insurance_Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Account_Address__c.field-meta.xml
<CustomField>
    <fullName>Account_Address__c</fullName>
    <formula>Account__r.Name  &amp; BR() &amp; Account__r.BillingStreet &amp; BR() &amp; Account__r.BillingCity &amp; &quot; &quot; &amp; Account__r.BillingState &amp; &quot; &quot;&amp; Account__r.BillingPostalCode &amp; BR() &amp; Account__r.BillingCountry</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Amount_Paid_Rollup__c.field-meta.xml
<CustomField>
    <fullName>Amount_Paid_Rollup__c</fullName>
    <label>Amount Paid</label>
    <summarizedField>Payment_Transaction__c.Amount_Paid__c</summarizedField>
    <summaryFilterItems>
        <field>Payment_Transaction__c.Status__c</field>
        <operation>equals</operation>
        <value>Successful</value>
    </summaryFilterItems>
    <summaryForeignKey>Payment_Transaction__c.Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Balance_Amount__c.field-meta.xml
<CustomField>
    <fullName>Balance_Amount__c</fullName>
    <formula>Total_Amount__c -  Amount_Paid_Rollup__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Balance Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CAD</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Internal_Notes__c.field-meta.xml
<CustomField>
    <fullName>Internal_Notes__c</fullName>
    <label>Internal Notes</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Invoice_Amount__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Amount__c</fullName>
    <description>To capture amount to be payed as per the invoice.</description>
    <inlineHelpText>Amount to be Payed.</inlineHelpText>
    <label>Invoice Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Policy</label>
    <referenceTo>InsurancePolicy</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Invoice Generation &amp; Payment Status</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Tax_1__c.field-meta.xml
<CustomField>
    <fullName>Tax_1__c</fullName>
    <label>Tax 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Tax_2__c.field-meta.xml
<CustomField>
    <fullName>Tax_2__c</fullName>
    <label>Tax 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Tax_3__c.field-meta.xml
<CustomField>
    <fullName>Tax_3__c</fullName>
    <label>Tax 3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Tax_Amount_Percent_1__c.field-meta.xml
<CustomField>
    <fullName>Tax_Amount_Percent_1__c</fullName>
    <label>Tax Amount Percent 1</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Tax_Amount_Percent_2__c.field-meta.xml
<CustomField>
    <fullName>Tax_Amount_Percent_2__c</fullName>
    <label>Tax Amount Percent 2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Tax_Amount_Percent_3__c.field-meta.xml
<CustomField>
    <fullName>Tax_Amount_Percent_3__c</fullName>
    <label>Tax Amount Percent 3</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <formula>Total_Line_Items_Amount__c +  Total_Tax_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Total_Line_Items_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Line_Items_Amount__c</fullName>
    <label>Total Line Items Amount</label>
    <summarizedField>Invoice_Line_Items__c.Amount__c</summarizedField>
    <summaryForeignKey>Invoice_Line_Items__c.Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Items__c/Invoice_Line_Items__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>ILI-{0000}</displayFormat>
        <label>Invoice Line Items Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Line_Items__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <formula>Rate__c *   Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Items__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Items__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Rate</label>
    <precision>18</precision>
    <scale>13</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice_Taxes__c/Invoice_Taxes__c.object-meta.xml
<CustomObject>
    <label>Invoice Tax</label>
    <nameField>
        <displayFormat>ITAX-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Taxes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Taxes__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>If &quot;Override&quot; is checked, its value is Override Amount, otherwise it will be calculated Amount from Tax% defined in related Tax record.</description>
    <inlineHelpText>If &quot;Override&quot; is checked, its value is Override Amount, otherwise it will be calculated Amount from Tax% defined in related Tax record.</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice_Taxes__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Taxes</relationshipLabel>
    <relationshipName>Invoice_Taxes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Taxes__c/fields/Tax__c.field-meta.xml
<CustomField>
    <fullName>Tax__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tax</label>
    <referenceTo>Tax__c</referenceTo>
    <relationshipLabel>Invoice Taxes</relationshipLabel>
    <relationshipName>Invoice_Taxes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Taxes__c/fields/TaxPercent__c.field-meta.xml
<CustomField>
    <fullName>TaxPercent__c</fullName>
    <formula>Tax__r.Tax_Percent__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tax %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/Payment_Transaction__c.object-meta.xml
<CustomObject>
    <label>Payment Transaction</label>
    <nameField>
        <displayFormat>PTN-{0000}</displayFormat>
        <label>Payment Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Transaction__c/fields/Mode_of_Payment__c.field-meta.xml
<CustomField>
    <fullName>Mode_of_Payment__c</fullName>
    <label>Mode of Payment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bank Transfer</fullName>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tax__c/Tax__c.object-meta.xml
<CustomObject>
    <label>Tax</label>
    <nameField>
        <label>Tax Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Taxes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/InvoicePDFController.cls
/*
@Name             : InvoicePDFControlller
@Author           : Zain Abbas @ CloudJunction
@Date             : 28 Oct, 2019
@Description      : This class retrieves data for Invoice and it's related Objects.
					It's is the primary controller for Invoice VF PDF Page. 
*/

public class InvoicePDFController {
    
    public Map<Invoice__c , List<Invoice_Line_Items__c> > InvoiceLITMapLinetems{get;  set;}
    public map<string, string> footerMap {get; set;}
    public List<Invoice_Line_Items__c> InvoiceLines {get;set;}
    public List<Payment_Transaction__c> PaymentTransaction {get;set;}
    public list<Invoice_Taxes__c> listOfTaxes {get; set;}
    
    
    public Invoice__c[]  Invoice{get; set;}
    public Decimal InvoieLineTotal{get;  set;}
    public Date dates {get;set;}
    public String dat{get;set;}
    public Decimal Tax1Amount{get;set;}
    public Decimal Tax2Amount{get;set;}
    public Decimal Tax3Amount{get;set;}
    public string imageURL {get; set;}
    public string invNotes {get; set;}
    public string dispBankData {get;set;}
    public string Receipt {get; set;}
    public boolean isRecp {get; set;}	
    
    public InvoicePDFController (){
        try{
            imageURL = '';
            String InvoiceId= '';
            string FooterPhone = '';
            string FooterEmail = '';
            string FooterWeb = '';
            string FooterBussID = '';
            Tax1Amount = 0.0;
            Tax2Amount = 0.0;
            Tax3Amount = 0.0;
            listOfTaxes = new list<Invoice_Taxes__c>();
            invNotes = '';
            InvoiceId= apexpages.currentPage().getParameters().get('InvId');
          	Receipt = apexpages.currentPage().getParameters().get('recp') != null? apexpages.currentPage().getParameters().get('recp') : '0';
            
            system.debug('Receipt='+Receipt);
          
            InvoiceLines = new List<Invoice_Line_Items__c>();
            
            system.Debug('::Invoice Id: '+ InvoiceId);
            
            if(Receipt != '0'){
                isRecp = true;
            	PaymentTransaction = [Select id,name,Amount_Paid__c,Invoice__c,Mode_of_Payment__c,Internal_Notes__c,Payment_Date__c,Reference_Number__c,Status__c from Payment_Transaction__c where id =:Receipt];
            	system.debug('inside if');
            }
            else
                isRecp = false;
            system.debug('PaymentTransaction='+PaymentTransaction);
            footerMap = new map<string, string>();
            
            /*string ref = ApexPages.currentPage().getHeaders().get('Referer');
            system.debug('ref='+ref);
            */
            Invoice = new Invoice__c[]{};
                
            Invoice=[Select id, name, Amount__c, Policy__c,Policy__R.Policy_Holder__c, Invoice_Notes__c, Account_Address__c,Total_Line_Items_Amount__c,Amount_Paid_Rollup__c,
                     CreatedById,Currency__c,Balance_Amount__c,Description__c,Due_Date__c,Invoice_Amount__c,Invoice_Date__c,Internal_Notes__c,Status__c, createddate,
                     Tax_1__c,Tax_2__c,Tax_3__c,Tax_Amount_Percent_1__c,Tax_Amount_Percent_2__c,Tax_Amount_Percent_3__c, Total_Amount__c from Invoice__c where id=:InvoiceId];
            
            InvoiceLines= [Select id, name, Amount__c,Rate__c,Quantity__c,Description__c,Invoice__c from Invoice_Line_items__c where Invoice__c =:InvoiceId ORDER BY createddate ASC];
            
            
            
            listOfTaxes = [select id, name, Tax__r.name, Amount__c, TaxPercent__c from Invoice_Taxes__c where Invoice__c =:InvoiceId];
            
            system.Debug('::InvoiceLines: '+ InvoiceLines);
            
            if(Invoice[0].Invoice_Notes__c != null)
                invNotes = Invoice[0].Invoice_Notes__c;
            
            if(Invoice.size() > 0){
                DateTime dt = Invoice[0].createdDate;
                dates = date.newinstance(dT.year(), dT.month(), dT.day());
                
                dat = dT.month()+ '-' + dT.day()+ '-' +dT.year();
            }
            
            String myGeneratedFileName = Invoice[0].name+'.pdf';
            
            Apexpages.currentPage().getHeaders().put('content-disposition', 'inline; filename='+myGeneratedFilename);
            
            list<Document> filesList = [select id, Name from Document where name = 'Logo' or name = 'logo'];
            if(filesList.size() > 0)
                imageURL = filesList[0].id;
            system.debug('imageURL='+imageURL);
            
            FooterPhone = label.PDF_Footer_Phone;
            FooterEmail = label.PDF_Footer_Email;
            FooterWeb = label.PDF_Footer_Web;
            FooterBussID = label.PDF_Footer_Business_Tax_ID;
            
            if(!string.isBlank(FooterPhone) && FooterPhone.contains(':')){
                string[] phoneArr = FooterPhone.split(':');
                footerMap.put(phoneArr[0], phoneArr[1]);
                
            }
            if(!string.isBlank(FooterEmail) && FooterEmail.contains(':')){
                string[] emailArr = FooterEmail.split(':');
                footerMap.put(emailArr[0], emailArr[1]);
                
            }
            if(!string.isBlank(FooterWeb) && FooterWeb.contains(':')){
                string[] webArr = FooterWeb.split(':');
                footerMap.put(webArr[0], webArr[1]);
                
            }
            if(!string.isBlank(FooterBussID) && FooterBussID.contains(':')){
                string[] bussIDArr = FooterBussID.split(':');
                footerMap.put(bussIDArr[0], bussIDArr[1]); 
                
            }
            
        }
        catch(Exception Ex){
            system.Debug('::Exception LineNumber: '+ex.getLineNumber());
            system.Debug('::Exception Message: ' +ex.getMessage());
            system.Debug('::Exception Cause: '+ex.getCause());
            system.Debug('::Exception Type Name:  '+ex.getTypeName());
        }
    }
}