force-app/main/default/objects/InsurancePolicy/fields/Policy_Holder__c.field-meta.xml
<CustomField>
    <fullName>Policy_Holder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Policy Holder of the policy</inlineHelpText>
    <label>Policy Holder</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Insurance Policies (Policy Holder)</relationshipLabel>
    <relationshipName>Insurance_Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/Policy_LImit__c.field-meta.xml
<CustomField>
    <fullName>Policy_LImit__c</fullName>
    <label>Policy LImit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Quote from where policy originated.</inlineHelpText>
    <label>Source Quote</label>
    <referenceTo>Quote2__c</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Aggregate__c.field-meta.xml
<CustomField>
    <fullName>Aggregate__c</fullName>
    <inlineHelpText>Aggregate of policy product</inlineHelpText>
    <label>Aggregate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Parent_Product__c.field-meta.xml
<CustomField>
    <fullName>Parent_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Policy Product</inlineHelpText>
    <label>Product Option</label>
    <referenceTo>CoverageType</referenceTo>
    <relationshipLabel>Policy Product Details</relationshipLabel>
    <relationshipName>Policy_Product_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Policy_Limit__c.field-meta.xml
<CustomField>
    <fullName>Policy_Limit__c</fullName>
    <inlineHelpText>Policy limit applied on a policy product</inlineHelpText>
    <label>Policy Limit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote2__c/Quote2__c.object-meta.xml
<CustomObject>
    <description>Quote is a bundle of different products with Policy Options and Product Coverages, customized specifically for each opportunity. This object will only be associated with Business companies. There can be multiple quotes associated with the opportunity, to track multiple quotes, there will be a status field which will have options like Draft, Activated, Rejected and only one quote can have ‘activated’ status under one opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote2__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Account of a quote</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Master_Policies</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote2__c/fields/Policy_Limit__c.field-meta.xml
<CustomField>
    <fullName>Policy_Limit__c</fullName>
    <label>Policy Limit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote2__c/fields/Quote_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Quote_Effective_Date__c</fullName>
    <inlineHelpText>Effective date of the quote</inlineHelpText>
    <label>Policy Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote2__c/fields/Quote_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Quote_Expiry_Date__c</fullName>
    <inlineHelpText>Expiry date of the quote</inlineHelpText>
    <label>Quote Expiry Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Tax__c/Tax__c.object-meta.xml
<CustomObject>
    <label>Tax</label>
    <nameField>
        <label>Tax Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Taxes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tax__c/fields/Province__c.field-meta.xml
<CustomField>
    <fullName>Province__c</fullName>
    <label>Province</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alberta</fullName>
            </value>
            <value>
                <fullName>British Columbia</fullName>
            </value>
            <value>
                <fullName>Manitoba</fullName>
            </value>
            <value>
                <fullName>New Brunswick</fullName>
            </value>
            <value>
                <fullName>Newfoundland and Labrador</fullName>
            </value>
            <value>
                <fullName>Northwest Territories</fullName>
            </value>
            <value>
                <fullName>Nova Scotia</fullName>
            </value>
            <value>
                <fullName>Nunavut</fullName>
            </value>
            <value>
                <fullName>Ontario</fullName>
            </value>
            <value>
                <fullName>Prince Edward Island</fullName>
            </value>
            <value>
                <fullName>Quebec</fullName>
            </value>
            <value>
                <fullName>Saskatchewan</fullName>
            </value>
            <value>
                <fullName>Yukon</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tax__c/fields/Tax_Percent__c.field-meta.xml
<CustomField>
    <fullName>Tax_Percent__c</fullName>
    <label>Tax %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/PresentQuote.cls
public without sharing class PresentQuote {
    public PresentQuote() {

    }

    @AuraEnabled
    public static InsurancePolicy getInsurancePolicy(){


        Account acc = PersonInformation.getAccountRecord();

        InsurancePolicy certInfo = [Select id, name , NameInsuredId, NameInsured.FirstName, 
        NameInsured.LastName, NameInsured.PersonMailingAddress, Quote__c, 
        NameInsured.PersonEmail, Policy_Holder__r.Name, Product.Name,
        Quote__r.Name, Quote__r.Account__r.Name, 
        NameInsured.Phone,
        NameInsured.BillingState,
        Quote__r.Quote_Effective_Date__c,
        Discount,
        Quote__r.Quote_Expiry_Date__c ,
        PremiumAmount from InsurancePolicy where NameInsuredId=:acc.Id LIMIT 1];

        return certInfo;

    }

    @AuraEnabled
    public static List<InsurancePolicyCoverage> getPPD(Id insuranceId){



        System.debug('Insurance Id::' + insuranceId);

        List<InsurancePolicyCoverage> certInfo = [Select id, name , DeductibleAmount, PremiumAmount,
        Policy_Limit__c , Aggregate__c, Parent_Product__c from InsurancePolicyCoverage 
        where InsurancePolicyId =: insuranceId];


        System.debug('List of PPD::' + certInfo );

        return certInfo;

    }

    @AuraEnabled
    public static Decimal getTax(String BillingState){
        try {
 
            Tax__c taxOfBS = [Select id, name , Tax_Percent__c, Province__c from tax__c where Province__c =: BillingState LIMIT 1];

            return taxOfBS.Tax_Percent__c;

        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}